package com.supremeai.service;

import org.springframework.stereotype.Service;

import java.util.LinkedHashMap;
import java.util.Map;

@Service
public class CodeGenerationService {

    /**
     * Generate a simple skeleton application based on spec.
     * This is a minimal taste-phase implementation - returns static template.
     */
    public Map<String, Object> generate(Map<String, Object> spec) {
        String appName = (String) spec.getOrDefault("name", "MyApp");
        Map<String, String> files = new LinkedHashMap<>();

        // Generate a basic Gradle build file
        String buildGradle = """
            plugins {
                id("org.springframework.boot") version "3.2.3"
                id("io.spring.dependency-management") version "1.1.4"
                java
            }
            group = "com.example"
            version = "1.0.0"
            java {
                sourceCompatibility = JavaVersion.VERSION_17
            }
            repositories {
                mavenCentral()
            }
            dependencies {
                implementation("org.springframework.boot:spring-boot-starter-web")
                testImplementation("org.springframework.boot:spring-boot-starter-test")
            }
            tasks.getByName("test") {
                useJUnitPlatform()
            }
            """;
        files.put("build.gradle.kts", buildGradle);

        // Generate a simple main application class
        String appClass = """
            package com.example.%s;

            import org.springframework.boot.SpringApplication;
            import org.springframework.boot.autoconfigure.SpringBootApplication;

            @SpringBootApplication
            public class %sApplication {
                public static void main(String[] args) {
                    SpringApplication.run(%sApplication.class, args);
                }
            }
            """.formatted(appName.toLowerCase(), appName, appName);
        files.put("src/main/java/com/example/" + appName.toLowerCase() + "/" + appName + "Application.java", appClass);

        // Generate a simple REST controller
        String controller = """
            package com.example.%s.controller;

            import org.springframework.web.bind.annotation.GetMapping;
            import org.springframework.web.bind.annotation.RequestMapping;
            import org.springframework.web.bind.annotation.RestController;

            @RestController
            @RequestMapping("/api")
            public class HelloController {
                @GetMapping("/hello")
                public String hello() {
                    return "Hello from %s!";
                }
            }
            """.formatted(appName.toLowerCase(), appName, appName);
        files.put("src/main/java/com/example/" + appName.toLowerCase() + "/controller/HelloController.java", controller);

        // Generate application.yml
        String yml = """
            server:
              port: 8080
            spring:
              application:
                name: %s
            """;
        files.put("src/main/resources/application.yml", yml);

        // Generate README
        String readme = """
            # %s
            Generated by SupremeAI (taste phase).
            - Run with: ./gradlew bootRun
            - Access: http://localhost:8080/api/hello
            """.formatted(appName);
        files.put("README.md", readme);

        Map<String, Object> result = new LinkedHashMap<>();
        result.put("appName", appName);
        result.put("files", files);
        result.put("fileCount", files.size());
        result.put("status", "GENERATED");
        result.put("message", "Skeleton app generated (taste phase)");
        return result;
    }
}
