default_platform(:android)

platform :android do
  desc "Build and deploy to Google Play (Internal track by default)"
  lane :deploy do
    # 1. Update version codes if needed (optional)
    # flutter build takes care of this usually or fastlane can bump versions
    
    # 2. Build the app using flutter
    sh "cd ../../ && flutter build appbundle --release"

    # 3. Upload to Google Play
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
