// Auto-generated by SupremeAI Type Generator
// Source: schemas.skill_manifest.SkillGovernance

// ignore_for_file: prefer_final_fields, non_constant_identifier_names

/// Runtime contract for a published skill.

The defaults deliberately deny data, tools, and execution approvals.  A skill
must opt in to every capability in its manifest instead of inheriting broad
platform access.
class SkillGovernance {
  null owner;
  List<null> allowedData;
  List<null> allowedRoles;
  List<null> toolsAllowed;
  Map<null, null> humanApprovalPoints;
  Map<null, null> successMetrics;
  List<null> evaluationTests;
  Map<null, null> budget;
  List<null> auditLogging;

  SkillGovernance({
    required this.owner,
    this.allowedData,
    this.allowedRoles,
    this.toolsAllowed,
    this.humanApprovalPoints,
    this.successMetrics,
    this.evaluationTests,
    this.budget,
    this.auditLogging,
  });

  factory SkillGovernance.fromJson(Map<String, dynamic> json) {
    return SkillGovernance(
      owner: json['owner'] as null,
      allowedData: json['allowedData'] as List<null>,
      allowedRoles: json['allowedRoles'] as List<null>,
      toolsAllowed: json['toolsAllowed'] as List<null>,
      humanApprovalPoints: json['humanApprovalPoints'] as Map<null, null>,
      successMetrics: json['successMetrics'] as Map<null, null>,
      evaluationTests: json['evaluationTests'] as List<null>,
      budget: json['budget'] as Map<null, null>,
      auditLogging: json['auditLogging'] as List<null>,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'owner': owner,
      'allowedData': allowedData,
      'allowedRoles': allowedRoles,
      'toolsAllowed': toolsAllowed,
      'humanApprovalPoints': humanApprovalPoints,
      'successMetrics': successMetrics,
      'evaluationTests': evaluationTests,
      'budget': budget,
      'auditLogging': auditLogging,
    };
  }
}
