// Auto-generated by SupremeAI Type Generator
// Source: schemas.skill_manifest.SkillManifest

// ignore_for_file: prefer_final_fields, non_constant_identifier_names

class SkillManifest {
  null skillId;
  null name;
  null description;
  null version;
  null sourceUrl;
  null checksum;
  null status;
  null permissions;
  any governance;
  null usageCount;
  null failureCount;
  any lastUsedAt;
  null createdAt;
  any expiresAt;

  SkillManifest({
    required this.skillId,
    required this.name,
    required this.description,
    this.version,
    required this.sourceUrl,
    required this.checksum,
    this.status,
    this.permissions,
    this.governance,
    this.usageCount,
    this.failureCount,
    this.lastUsedAt,
    this.createdAt,
    this.expiresAt,
  });

  factory SkillManifest.fromJson(Map<String, dynamic> json) {
    return SkillManifest(
      skillId: json['skillId'] as null,
      name: json['name'] as null,
      description: json['description'] as null,
      version: json['version'] as null,
      sourceUrl: json['sourceUrl'] as null,
      checksum: json['checksum'] as null,
      status: json['status'] as null,
      permissions: json['permissions'] as null,
      governance: json['governance'] as any,
      usageCount: json['usageCount'] as null,
      failureCount: json['failureCount'] as null,
      lastUsedAt: json['lastUsedAt'] as any,
      createdAt: json['createdAt'] as null,
      expiresAt: json['expiresAt'] as any,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'skillId': skillId,
      'name': name,
      'description': description,
      'version': version,
      'sourceUrl': sourceUrl,
      'checksum': checksum,
      'status': status,
      'permissions': permissions,
      'governance': governance,
      'usageCount': usageCount,
      'failureCount': failureCount,
      'lastUsedAt': lastUsedAt,
      'createdAt': createdAt,
      'expiresAt': expiresAt,
    };
  }
}
