// Auto-generated by SupremeAI Type Generator
// Source: schemas.skill_manifest.SkillPermissions

// ignore_for_file: prefer_final_fields, non_constant_identifier_names

class SkillPermissions {
  null allowNetwork;
  List<null> allowedDomains;
  null allowFilesystemWrite;
  List<null> requiredEnvVars;

  SkillPermissions({
    this.allowNetwork,
    this.allowedDomains,
    this.allowFilesystemWrite,
    this.requiredEnvVars,
  });

  factory SkillPermissions.fromJson(Map<String, dynamic> json) {
    return SkillPermissions(
      allowNetwork: json['allowNetwork'] as null,
      allowedDomains: json['allowedDomains'] as List<null>,
      allowFilesystemWrite: json['allowFilesystemWrite'] as null,
      requiredEnvVars: json['requiredEnvVars'] as List<null>,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'allowNetwork': allowNetwork,
      'allowedDomains': allowedDomains,
      'allowFilesystemWrite': allowFilesystemWrite,
      'requiredEnvVars': requiredEnvVars,
    };
  }
}
