import os

from github import Github
from loguru import logger

from tools.github_agent import GitHubAgent


class AutoRemediationEngine:
    def __init__(self):
        self.github_client = Github(os.getenv("GITHUB_TOKEN"))
        self.repo = self.github_client.get_repo(
            os.getenv("GITHUB_REPOSITORY", "paykaribazaronline/supremeai")
        )
        self._model = None

    def process_codeql_alert(
        self, file_path: str, line_number: int, vulnerability_details: str
    ):
        """CodeQL অ্যালার্ট প্রসেস করে অটোমেটিক PR ওপেন করে"""
        try:
            # 1. গিটহাব থেকে অরিজিনাল কোড ফেচ করা
            file_content = self.repo.get_contents(file_path).decoded_content.decode(
                "utf-8"
            )

            # 2. Gemini দিয়ে সিকিউর প্যাচ জেনারেট করা
            patch_code = self._generate_ai_patch(
                file_content, line_number, vulnerability_details
            )

            if patch_code:
                # 3. অটোমেটিক Branch এবং PR তৈরি করা
                self._create_remediation_pr(
                    file_path, file_content, patch_code, vulnerability_details
                )
                logger.info(f"✅ Auto-Remediation PR created for {file_path}")

        except Exception as e:
            logger.error(f"❌ Remediation failed: {str(e)}")

    def _generate_ai_patch(self, code: str, line: int, issue: str) -> str:
        # বাংলা মন্তব্য: লঞ্চডার্কলি এজেন্টস কন্ট্রোল এবং ভ্যারিয়েবল ইভ্যালুয়েশন লজিক যুক্ত করা হলো
        from ldai import AICompletionConfigDefault
        from ldai import LDMessage
        from ldai import ModelConfig
        from ldclient.context import Context

        from core.ld_client import ld_ai_client

        default_prompt_template = """You are an elite AI AppSec Engineer. Fix the following vulnerability.
        Issue: {issue} at line {line}.
        Return ONLY the fully corrected Python code. No markdown formatting blocks, no explanations.

        Original Code:
        {code}
        """

        context = Context.builder("auto-remediation-engine").kind("service").build()
        prompt_vars = {
            "issue": issue,
            "line": str(line),
            "code": code
        }

        config = None
        if ld_ai_client:
            try:
                config = ld_ai_client.completion_config(
                    os.getenv("LAUNCHDARKLY_AI_CONFIG_KEY", "auto-remediation-patch"),
                    context,
                    default=AICompletionConfigDefault(
                        enabled=True,
                        model=ModelConfig(name="gemini/gemini-1.5-pro"),
                        messages=[
                            LDMessage(role="system", content=default_prompt_template)
                        ]
                    ),
                    variables=prompt_vars
                )
            except Exception as exc:
                logger.warning(f"LaunchDarkly config evaluation failed, falling back: {exc}")

        if config and config.enabled:
            model_name = config.model.name if config.model else "gemini/gemini-1.5-pro"
            prompt = config.messages[0].content if config.messages else default_prompt_template.format(**prompt_vars)
        else:
            model_name = "gemini/gemini-1.5-pro"
            prompt = default_prompt_template.format(**prompt_vars)

        import asyncio

        from core.llm_gateway import llm_gateway
        response = asyncio.run(llm_gateway.acompletion(
            prompt=prompt,
            task_type="coding",
            stream=False,
            model=model_name
        ))
        result = response.get("text", "") if isinstance(response, dict) else str(response)
        return result.strip()

    def _create_remediation_pr(
        self, file_path: str, old_code: str, new_code: str, issue: str
    ):
        branch_name = f"auto-fix/security-patch-{os.urandom(4).hex()}"
        main_branch = self.repo.get_branch("main")
        self.repo.create_git_ref(
            ref=f"refs/heads/{branch_name}", sha=main_branch.commit.sha
        )

        self.repo.update_file(
            path=file_path,
            message=f"🛡️ Auto-Remediation: Fixed {issue}",
            content=new_code,
            sha=self.repo.get_contents(file_path).sha,
            branch=branch_name,
        )

        self.repo.create_pull(
            title=f"🚨 Security Auto-Patch: {file_path}",
            body=f"This PR was automatically generated by SupremeAI Immune System to fix: **{issue}**.",
            head=branch_name,
            base="main",
        )


class AutoRemediation:
    """
    Autonomous Auto-Remediation Loop (Compatibility / Mockable Wrapper for tests).
    Detects CodeQL or security alerts, calls Gemini to get a secure patch,
    applies it, and creates a GitHub Pull Request for evaluation.
    """

    def __init__(self, gemini_api_key: str | None = None):
        self.gemini_api_key = gemini_api_key or os.getenv("GEMINI_API_KEY", "")
        self.github_agent = GitHubAgent()

    def process_security_alert(
        self, file_path: str, line_number: int, issue: str, severity: str
    ) -> dict:
        logger.info(
            f"Auto-Remediation triggered for {file_path}:{line_number} - Severity: {severity}. Issue: {issue}"
        )

        # 1. Read the original vulnerable file content
        if not os.path.exists(file_path):
            return {"success": False, "error": f"File {file_path} not found"}

        with open(file_path, encoding="utf-8") as f:
            original_code = f.read()

        # 2. Query Gemini for the secure patch
        fixed_code = self._get_ai_patch(file_path, original_code, line_number, issue)
        if not fixed_code:
            return {"success": False, "error": "AI failed to generate a secure patch"}

        # 3. Apply the patch (Write to the file) with validation
        try:
            import ast

            if fixed_code.strip() and not fixed_code.strip().startswith("#"):
                ast.parse(fixed_code)
        except SyntaxError as se:
            logger.error(f"AI-generated patch failed validation: {se}")
            return {
                "success": False,
                "error": f"Generated patch contains invalid syntax: {se}",
            }

        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(fixed_code)
            logger.info(f"Patch applied successfully to {file_path}")
        except Exception as e:
            return {"success": False, "error": f"Failed to apply patch to file: {e}"}

        # Attempt to commit the change, but don't fail if token is missing
        commit_message = f"🛡️ Auto-Remediation: Fixed {issue}"
        try:
            self.github_agent.commit_changes(
                repo_url="paykaribazaronline/supremeai",
                files_to_commit=[file_path],
                commit_message=commit_message,
                branch="main",
            )
            logger.info(f"Directly committed fix for {issue} to main branch.")
        except RuntimeError as e:
            if "GitHub token is required" in str(e):
                logger.warning(
                    f"GitHub token not available; patch applied locally but not committed: {e}"
                )
            else:
                raise

        return {
            "success": True,
            "file": file_path,
            "patch_applied": True,
            "branch": "supremeai-improvements",
            "pr_url": None,
            "message": "Remediation patch applied and committed.",
        }

    def _get_ai_patch(
        self, file_path: str, code: str, line_number: int, issue: str
    ) -> str:
        # বাংলা মন্তব্য: লঞ্চডার্কলি এজেন্টস কন্ট্রোল এবং ভ্যারিয়েবল ইভ্যালুয়েশন লজিক যুক্ত করা হলো
        from ldai import AICompletionConfigDefault
        from ldai import LDMessage
        from ldai import ModelConfig
        from ldclient.context import Context

        from core.ld_client import ld_ai_client

        default_prompt_template = """You are an elite secure coding assistant. Correct the security vulnerability in this file.
        File: {file_path}
        Line Number of Vulnerability: {line_number}
        Vulnerability Description: {issue}

        Provide the complete corrected file contents. Do NOT explain the changes. Return ONLY the code in plaintext with no markdown code blocks.

        Original Code:
        {code}
        """

        context = Context.builder("auto-remediation-helper").kind("service").build()
        prompt_vars = {
            "file_path": file_path,
            "line_number": str(line_number),
            "issue": issue,
            "code": code
        }

        config = None
        if ld_ai_client:
            try:
                config = ld_ai_client.completion_config(
                    os.getenv("LAUNCHDARKLY_AI_CONFIG_KEY", "auto-remediation-patch"),
                    context,
                    default=AICompletionConfigDefault(
                        enabled=True,
                        model=ModelConfig(name="gemini/gemini-1.5-pro"),
                        messages=[
                            LDMessage(role="system", content=default_prompt_template)
                        ]
                    ),
                    variables=prompt_vars
                )
            except Exception as exc:
                logger.warning(f"LaunchDarkly config evaluation failed, falling back: {exc}")

        if config and config.enabled:
            model_name = config.model.name if config.model else "gemini/gemini-1.5-pro"
            prompt = config.messages[0].content if config.messages else default_prompt_template.format(**prompt_vars)
        else:
            model_name = "gemini/gemini-1.5-pro"
            prompt = default_prompt_template.format(**prompt_vars)

        try:
            import asyncio

            from core.llm_gateway import llm_gateway
            response = asyncio.run(llm_gateway.acompletion(
                prompt=prompt,
                task_type="coding",
                stream=False,
                model=model_name
            ))
            raw_text = response.get("text", "") if isinstance(response, dict) else str(response)

            # Strip markdown formatting if the model returned any
            if raw_text.strip().startswith("```"):
                lines = raw_text.strip().splitlines()
                if len(lines) > 1:
                    if lines[0].startswith("```"):
                        lines = lines[1:]
                    if lines and lines[-1].startswith("```"):
                        lines = lines[:-1]
                    raw_text = "\n".join(lines)

            return raw_text.strip()
        except Exception as e:
            logger.error(f"Failed to generate patch from Gemini: {e}")
            return ""
