"""This module provides comprehensive validation utilities for various types of content, including AI-generated Python code, file paths, and URLs. It plays a critical role in the SupremeAI project by acting as a gatekeeper, ensuring the safety, correctness, and reliability of outputs generated by AI agents before they are executed or utilized, thereby preventing common errors, security risks, and unexpected behavior.

Key Components:
- `AICodeValidator`: A specialized class for performing detailed static analysis and validation on AI-generated Python code, checking for syntax, indentation, import validity, variable definition, and potential infinite loops.
- `AICodeValidator.validate_before_use()`: Orchestrates a series of validation checks on Python code and returns a consolidated report, including an attempt at auto-fixing minor issues.
- `AICodeValidator._check_syntax()`: Verifies the basic syntactic correctness of Python code.
- `AICodeValidator._check_indentation()`: Checks for proper Python indentation.
- `AICodeValidator._check_imports_exist()`: Ensures that all imported modules are discoverable within the Python environment or are recognized internal SupremeAI modules.
- `AICodeValidator._module_exists()`: A helper method to determine if a given module name corresponds to an existing or recognized Python module.
- `AICodeValidator._check_variables_defined()`: Analyzes Python code to ensure all variables used are properly defined within their scope.
- `AICodeValidator._check_loop_safety()`: Identifies potentially unsafe `while True` loops that lack explicit `break` or `return` statements.
- `AICodeValidator._auto_fix()`: Applies simple, heuristic-based fixes to common Python code issues, such as missing colons in definitions.
- `CodeValidator`: A higher-level validator that integrates Python code validation with checks for file system paths and URLs, and can parse and validate components within a larger text string.
- `CodeValidator.validate_syntax()`: Delegates Python code validation to `AICodeValidator` and formats the results.
- `CodeValidator.validate_path()`: Checks the existence and type (file/directory) of a given file system path.
- `CodeValidator.validate_url()`: Validates the structural correctness of a URL and applies project-specific blacklisting rules.
- `CodeValidator.validate()`: Scans a general text string for embedded Python code blocks and URLs, performing comprehensive validation on each found element.

Dependencies:
- `ast`: Used for parsing Python code into an Abstract Syntax Tree for static analysis.
- `os`: Provides functions for interacting with the operating system, primarily for file path validation.
- `re`: Utilized for regular expression operations to extract Python code blocks and URLs from text.
- `urllib.parse`: For parsing and validating URL structures.
- `importlib.util`: Employed to dynamically check for the existence of Python modules.
- `builtins`: Accessed to identify and filter out Python's built-in names during variable definition checks.
- `loguru.logger`: For structured logging of validation failures (anti-silent-failure).
- `core.error_bus.with_error_bus`: For automatic error reporting to the ErrorEventBus.
"""

import ast
import os
import re
import urllib.parse

from loguru import logger

from core.error_bus import with_error_bus


class AICodeValidator:
    def validate_before_use(self, ai_generated_code: str) -> dict:
        checks = {
            "syntax_valid": self._check_syntax(ai_generated_code),
            "indentation_correct": self._check_indentation(ai_generated_code),
            "no_hallucinated_imports": self._check_imports_exist(ai_generated_code),
            "no_undefined_variables": self._check_variables_defined(ai_generated_code),
            "no_infinite_loops": self._check_loop_safety(ai_generated_code),
        }
        all_passed = all(checks.values())
        return {
            "can_use": all_passed,
            "checks": checks,
            "fixed_code": (self._auto_fix(ai_generated_code) if not all_passed else ai_generated_code),
        }

    def _check_syntax(self, code: str) -> bool:
        try:
            ast.parse(code)
            return True
        except SyntaxError as exc:
            logger.debug(f"[AICodeValidator] Syntax error: {exc}")
            return False

    def _check_indentation(self, code: str) -> bool:
        try:
            ast.parse(code)
            return True
        except IndentationError as exc:
            logger.debug(f"[AICodeValidator] Indentation error: {exc}")
            return False
        except SyntaxError as e:
            return not ("unexpected indent" in str(e) or "unindent does not match" in str(e))

    @with_error_bus("_check_imports_exist")
    def _check_imports_exist(self, code: str) -> bool:
        try:
            tree = ast.parse(code)
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        if not self._module_exists(alias.name):
                            return False
                elif isinstance(node, ast.ImportFrom) and not self._module_exists(node.module):
                    return False
            return True
        except Exception as exc:
            logger.error(f"[AICodeValidator] _check_imports_exist failed: {exc}")
            return False

    @with_error_bus("_module_exists")
    def _module_exists(self, module_name: str) -> bool:
        if not module_name:
            return False
        base_module = module_name.split(".", maxsplit=1)[0]
        # Ignore custom local modules that might not be in path
        if base_module in ["core", "brain", "interfaces", "skills"]:
            return True
        import importlib.util

        try:
            spec = importlib.util.find_spec(base_module)
            return spec is not None
        except Exception as exc:
            logger.error(f"[AICodeValidator] _module_exists failed for '{module_name}': {exc}")
            return False

    @with_error_bus("_check_variables_defined")
    def _check_variables_defined(self, code: str) -> bool:
        try:
            tree = ast.parse(code)
            defined = set()
            used = set()
            for node in ast.walk(tree):
                if isinstance(node, ast.Name):
                    if isinstance(node.ctx, ast.Store):
                        defined.add(node.id)
                    elif isinstance(node.ctx, ast.Load):
                        used.add(node.id)
                elif isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
                    defined.add(node.name)
                    for arg in node.args.args:
                        defined.add(arg.arg)
                    if node.args.vararg:
                        defined.add(node.args.vararg.arg)
                    if node.args.kwarg:
                        defined.add(node.args.kwarg.arg)
                elif isinstance(node, ast.ClassDef):
                    defined.add(node.name)

            import builtins

            builtin_names = set(dir(builtins))
            undefined = used - defined - builtin_names
            # Allow common placeholder/external calls like some_async_func or test mocks if they are called as functions
            for node in ast.walk(tree):
                if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
                    undefined.discard(node.func.id)

            return len(undefined) == 0
        except Exception as exc:
            logger.error(f"[AICodeValidator] _check_variables_defined failed: {exc}")
            return False

    @with_error_bus("_check_loop_safety")
    def _check_loop_safety(self, code: str) -> bool:
        try:
            tree = ast.parse(code)
            for node in ast.walk(tree):
                if isinstance(node, ast.While) and (isinstance(node.test, ast.Constant) and node.test.value is True):
                    has_break = False
                    for subnode in ast.walk(node):
                        if isinstance(subnode, ast.Break | ast.Return):
                            has_break = True
                            break
                    if not has_break:
                        return False
            return True
        except Exception as exc:
            logger.error(f"[AICodeValidator] _check_loop_safety failed: {exc}")
            return False

    def _auto_fix(self, code: str) -> str:
        # Simple auto-fix for missing colons in function and class definitions
        lines = code.split("\n")
        fixed_lines = []
        for line in lines:
            stripped_line = line.strip()
            if (stripped_line.startswith("def ") or stripped_line.startswith("class ")) and not stripped_line.endswith(
                ":"
            ):
                line += ":"
            fixed_lines.append(line)
        code = "\n".join(fixed_lines)
        return code


class CodeValidator:
    def __init__(self):
        self.ai_validator = AICodeValidator()

    def validate_syntax(self, code: str, language: str = "python") -> dict:
        if language.lower() == "python":
            res = self.ai_validator.validate_before_use(code)
            is_valid = res["can_use"]
            return {
                "is_valid": is_valid,
                "valid": is_valid,
                "errors": (
                    [
                        {
                            "message": "AICodeValidator check failed",
                            "checks": res["checks"],
                        }
                    ]
                    if not is_valid
                    else []
                ),
            }
        return {"is_valid": True, "valid": True, "errors": []}

    def validate_path(self, path: str) -> dict:
        exists = os.path.exists(path)
        if not exists:
            clean_path = path.strip().replace("file:///", "").replace("/", os.sep)
            exists = os.path.exists(clean_path)

        return {
            "exists": exists,
            "is_file": os.path.isfile(path) if exists else False,
            "is_dir": os.path.isdir(path) if exists else False,
        }

    def validate_url(self, url: str) -> dict:
        parsed = urllib.parse.urlparse(url)
        is_valid = bool(parsed.scheme and parsed.netloc)

        if "nadim9/supremeai" in url.lower():
            is_valid = False

        return {
            "is_valid": is_valid,
            "valid": is_valid,
            "scheme": parsed.scheme,
            "netloc": parsed.netloc,
        }

    def validate(self, text: str) -> dict:
        python_blocks = re.findall(r"```python\s*(.*?)\s*```", text, re.DOTALL)
        for block in python_blocks:
            syntax = self.validate_syntax(block, "python")
            if not syntax["is_valid"]:
                return {
                    "is_valid": False,
                    "reason": "Python syntax or validation error",
                    "errors": syntax["errors"],
                }

        urls = re.findall(r"https?://[^\s\)\`\]]+", text)
        for url in urls:
            url_val = self.validate_url(url)
            if not url_val["is_valid"]:
                return {
                    "is_valid": False,
                    "reason": f"Invalid or disallowed URL: {url}",
                }

        return {"is_valid": True}
