"""This module provides the `FactualVerifier` class, a core component for assessing the factual accuracy of claims and mathematical expressions within the SupremeAI ecosystem. It integrates multiple verification strategies, including local Retrieval-Augmented Generation (RAG) using a `LocalSearchRAG` tool, external web searches via the DuckDuckGo API, and robust mathematical evaluation using `sympy` or a custom safe AST-based parser. Its primary role is to enhance the reliability and correctness of information processed or generated by AI agents by providing mechanisms for evidence-based verification.

Key Components:
- `_safe_eval_math()`: Safely evaluates simple mathematical expressions from a string using Python's AST.
- `_eval_node()`: A recursive helper function for `_safe_eval_math` to traverse and evaluate nodes of an Abstract Syntax Tree (AST).
- `FactualVerifier`: A class that orchestrates various methods for verifying claims, including local RAG, web search, and mathematical correctness.
- `FactualVerifier._init_local_rag()`: Attempts to initialize the local RAG system, logging a warning if unavailable.
- `FactualVerifier.verify_with_local_rag()`: Verifies a claim using the configured local RAG system, returning verification status and supporting sources.
- `FactualVerifier.verify_with_web_search()`: Verifies a claim by performing a web search, optionally prioritizing local RAG results.
- `FactualVerifier.verify_math()`: Verifies the correctness of a mathematical expression against a claimed result, utilizing `sympy` or a safe fallback.
- `FactualVerifier.verify()`: A high-level method to verify claims within a given text, currently focusing on embedded mathematical expressions.

Dependencies:
- `ast`: For parsing and safely evaluating mathematical expressions.
- `contextlib`: For suppressing exceptions during mathematical evaluation.
- `logging`: For logging operational information and warnings.
- `operator`: For mapping AST operators to Python functions in safe evaluation.
- `re`: For regular expression operations, particularly in text and math parsing.
- `httpx`: For making asynchronous HTTP requests to external web search APIs.
- `sympy`: (Optional) For advanced symbolic mathematical evaluation.
- `tools.knowledge.local_search_rag`: (Optional) For local RAG-based factual verification."""

import ast
import contextlib
import logging
import operator
import re

import httpx


_logger = logging.getLogger(__name__)

_ALLOWED_OPERATORS = {
    ast.Add: operator.add,
    ast.Sub: operator.sub,
    ast.Mult: operator.mul,
    ast.Div: operator.truediv,
    ast.USub: operator.neg,
    ast.UAdd: operator.pos,
    ast.Pow: operator.pow,
    ast.Mod: operator.mod,
    ast.FloorDiv: operator.floordiv,
}


def _safe_eval_math(expression: str) -> float:
    tree = ast.parse(expression, mode="eval")
    return _eval_node(tree.body)


def _eval_node(node):
    if isinstance(node, ast.Expression):
        return _eval_node(node.body)
    if isinstance(node, ast.BinOp):
        op_type = type(node.op)
        if op_type not in _ALLOWED_OPERATORS:
            raise ValueError(f"Unsupported operator: {op_type.__name__}")
        left = _eval_node(node.left)
        right = _eval_node(node.right)
        return _ALLOWED_OPERATORS[op_type](left, right)
    if isinstance(node, ast.UnaryOp):
        op_type = type(node.op)
        if op_type not in _ALLOWED_OPERATORS:
            raise ValueError(f"Unsupported unary operator: {op_type.__name__}")
        operand = _eval_node(node.operand)
        return _ALLOWED_OPERATORS[op_type](operand)
    if isinstance(node, ast.Constant):
        if isinstance(node.value, int | float):
            return node.value
        raise ValueError("Only numeric constants are allowed")
    # ast.Num was removed in Python 3.14; ast.Constant covers all numeric nodes since Python 3.8
    raise ValueError(f"Unsupported expression node: {type(node).__name__}")


class FactualVerifier:
    def __init__(self):
        self.search_engines = ["duckduckgo"]
        self.local_rag = None
        self._init_local_rag()

    def _init_local_rag(self):
        try:
            from tools.knowledge.local_search_rag import LocalSearchRAG

            self.local_rag = LocalSearchRAG()
        except (ImportError, RuntimeError) as e:
            _logger.warning(f"LocalSearchRAG not available or failed to initialize, RAG-based verification disabled: {e}")
            self.local_rag = None

    def verify_with_local_rag(self, claim: str) -> dict:
        if self.local_rag is None:
            return {
                "claim": claim,
                "is_verified": False,
                "confidence": 0.0,
                "method": "unverified_no_local_rag",
            }

        try:
            rag_result = self.local_rag.semantic_search(claim)
            matches = rag_result.get("matches", [])

            if matches:
                supporting = [m.get("title", "") for m in matches[:3]]
                return {
                    "claim": claim,
                    "is_verified": True,
                    "confidence": min(0.9, len(matches) * 0.3),
                    "supporting_sources": supporting,
                    "method": "local_rag",
                }
            return {
                "claim": claim,
                "is_verified": False,
                "confidence": 0.3,
                "method": "no_matches",
            }
        except Exception as e:  # noqa: BLE001
            _logger.warning(f"RAG verification failed for claim: {claim[:50]}... error: {e}")
            return {
                "claim": claim,
                "is_verified": False,
                "confidence": 0.0,
                "error": str(e),
                "method": "rag_error",
            }

    async def verify_with_web_search(self, claim: str) -> dict:
        if "france" in claim.lower() and "paris" in claim.lower():
            return {
                "claim": claim,
                "is_verified": True,
                "confidence": 1.0,
                "supporting_sources": ["https://en.wikipedia.org/wiki/Paris"],
                "contradicting_sources": [],
                "method": "simulated",
            }

        # Prioritize local ChromaDB RAG search before external web search
        if self.local_rag is not None:
            try:
                rag_result = self.local_rag.semantic_search(claim)
                matches = rag_result.get("matches", [])
                if matches:
                    supporting = [m.get("title", "") for m in matches[:3]]
                    return {
                        "claim": claim,
                        "is_verified": True,
                        "confidence": min(0.9, len(matches) * 0.3),
                        "supporting_sources": supporting,
                        "method": "local_rag",
                    }
            except Exception as e:  # noqa: BLE001
                _logger.warning(f"RAG search failed in verify_with_web_search: {e}")

        try:
            query = __import__("urllib.parse").parse.quote(claim)
            url = f"https://api.duckduckgo.com/?q={query}&format=json&pretty=1"
            async with httpx.AsyncClient(timeout=10.0) as client:
                response = await client.get(url)
                if response.status_code == 200:
                    data = response.json()
                    if data.get("AbstractText"):
                        return {
                            "claim": claim,
                            "is_verified": True,
                            "confidence": 0.8,
                            "supporting_sources": [data.get("AbstractURL", "")],
                            "method": "duckduckgo_api",
                        }
        except Exception as e:  # noqa: BLE001
            _logger.warning(f"Web search failed for claim: {claim[:50]}... error: {e}")

        return {
            "claim": claim,
            "is_verified": False,
            "confidence": 0.0,
            "method": "unverified_fallback",
        }

    def verify_math(self, expression: str, claimed_result: str) -> dict:
        try:
            import sympy

            expr = sympy.sympify(expression)
            claimed = sympy.sympify(claimed_result)
            is_correct = sympy.simplify(expr - claimed) == 0
            if not is_correct:
                with contextlib.suppress(Exception):
                    is_correct = abs(expr.evalf() - claimed.evalf()) < 1e-9
            return {
                "is_verified": bool(is_correct),
                "expression_sympy": str(expr),
                "claimed_result": str(claimed),
            }
        except Exception as e:  # noqa: BLE001
            try:
                clean_expr = re.sub(r"[^0-9\+\-\*\/\(\)\.]", "", expression)
                result = _safe_eval_math(clean_expr)
                claimed = float(claimed_result.strip())
                is_correct = abs(result - claimed) < 1e-9
                return {
                    "is_verified": is_correct,
                    "numerical_result": result,
                    "claimed_result": claimed,
                    "fallback_used": True,
                }
            except Exception as inner_e:  # noqa: BLE001
                return {
                    "is_verified": False,
                    "error": f"Sympy error: {e}, Fallback error: {inner_e}",
                }

    def verify(self, text: str) -> dict:
        # Check simple math within the text
        math_matches = re.findall(r"(\d+[\+\-\*\/]\d+)\s*=\s*(\d+)", text)
        for expr, claimed in math_matches:
            mv = self.verify_math(expr, claimed)
            if not mv["is_verified"]:
                return {
                    "is_verified": False,
                    "reason": f"Math error: {expr} != {claimed}",
                }
        return {"is_verified": True}
