{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.resilience4j",
    "module": "resilience4j-retry",
    "version": "2.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-core",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "resilience4j-retry-2.1.0.jar",
          "url": "resilience4j-retry-2.1.0.jar",
          "size": 48542,
          "sha512": "fc7025548743558a9c8e4454f58f8d3461b35b46b53fed2ea614d97fbeb0be393877183e05367d912f541b6251a44818a535ce941bd02596fc20dda182876cc9",
          "sha256": "e2dd918093bc263f1d725d0c17beea31ce34cbbf56eecfb92dce82a3c479e7b5",
          "sha1": "afaad85737e3ae522ef3161bef4ac8d557e5c95b",
          "md5": "447108bdd4ba9dd26235508ad8da2c3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "io.github.resilience4j",
          "module": "resilience4j-core",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "resilience4j-retry-2.1.0.jar",
          "url": "resilience4j-retry-2.1.0.jar",
          "size": 48542,
          "sha512": "fc7025548743558a9c8e4454f58f8d3461b35b46b53fed2ea614d97fbeb0be393877183e05367d912f541b6251a44818a535ce941bd02596fc20dda182876cc9",
          "sha256": "e2dd918093bc263f1d725d0c17beea31ce34cbbf56eecfb92dce82a3c479e7b5",
          "sha1": "afaad85737e3ae522ef3161bef4ac8d557e5c95b",
          "md5": "447108bdd4ba9dd26235508ad8da2c3d"
        }
      ]
    }
  ]
}
