package com.supremeai.model;

import com.google.cloud.firestore.annotation.DocumentId;
import com.google.cloud.spring.data.firestore.Document;
import java.util.List;
import java.util.Date;

/**
 * TaskProviderAssignment - Maps task types to specific AI providers.
 * Auto-generated by capability analysis when new providers register.
 * Admin can override via UI.
 *
 * Supports 0 to ∞ providers per task - not limited to any fixed number.
 */
@Document(collectionName = "task_provider_assignments")
public class TaskProviderAssignment {

    @DocumentId
    private String id;

    /** Task type identifier (e.g., "code_generation", "bengali_translation") */
    private String taskType;

    /** Task display name */
    private String taskLabel;

    /** List of provider IDs assigned to this task */
    private List<String> providerIds;

    /** Minimum providers needed for voting */
    private Integer minProviders;

    /** Maximum providers allowed for voting (cost control) */
    private Integer maxProviders;

    /** Voting strategy: weighted_consensus, majority, avg_top_n */
    private String votingStrategy;

    /** Minimum capability score to participate (0.0-1.0) */
    private Double capabilityThreshold;

    /** Is this assignment active? */
    private Boolean isActive;

    /** Who created/configured this */
    private String createdBy;

    /** Auto or manual */
    private String assignmentSource; // "auto" or "manual"

    @com.google.cloud.firestore.annotation.ServerTimestamp
    private Date createdAt;

    @com.google.cloud.firestore.annotation.ServerTimestamp
    private Date updatedAt;

    public TaskProviderAssignment() {}

    public TaskProviderAssignment(String taskType, List<String> providerIds) {
        this.taskType = taskType;
        this.providerIds = providerIds;
        this.isActive = true;
        this.assignmentSource = "auto";
        this.votingStrategy = "weighted_consensus";
        this.capabilityThreshold = 0.7;
        this.minProviders = 3;
        this.maxProviders = 15;
    }

    // Getters and Setters
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getTaskType() { return taskType; }
    public void setTaskType(String taskType) { this.taskType = taskType; }

    public String getTaskLabel() { return taskLabel; }
    public void setTaskLabel(String taskLabel) { this.taskLabel = taskLabel; }

    public List<String> getProviderIds() { return providerIds; }
    public void setProviderIds(List<String> providerIds) { this.providerIds = providerIds; }

    public Integer getMinProviders() { return minProviders; }
    public void setMinProviders(Integer minProviders) { this.minProviders = minProviders; }

    public Integer getMaxProviders() { return maxProviders; }
    public void setMaxProviders(Integer maxProviders) { this.maxProviders = maxProviders; }

    public String getVotingStrategy() { return votingStrategy; }
    public void setVotingStrategy(String votingStrategy) { this.votingStrategy = votingStrategy; }

    public Double getCapabilityThreshold() { return capabilityThreshold; }
    public void setCapabilityThreshold(Double capabilityThreshold) { this.capabilityThreshold = capabilityThreshold; }

    public Boolean getActive() { return isActive; }
    public void setActive(Boolean active) { isActive = active; }

    public String getCreatedBy() { return createdBy; }
    public void setCreatedBy(String createdBy) { this.createdBy = createdBy; }

    public String getAssignmentSource() { return assignmentSource; }
    public void setAssignmentSource(String assignmentSource) { this.assignmentSource = assignmentSource; }

    public Date getCreatedAt() { return createdAt; }
    public void setCreatedAt(Date createdAt) { this.createdAt = createdAt; }

    public Date getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(Date updatedAt) { this.updatedAt = updatedAt; }
}