[mypy]
ignore_missing_imports = True
explicit_package_bases = True
no_implicit_optional = False
disable_error_code = attr-defined, assignment, index, operator, union-attr, var-annotated, arg-type, return, misc, no-redef, dict-item, has-type, syntax
