import re


filepath = r"c:\Users\n\supremeai\supremeai_2.0\backend\core\resilience\auto_remediation.py"
with open(filepath, encoding="utf-8") as f:
    content = f.read()

# 1. Remove AutoRemediationEngine completely
content = re.sub(r"class AutoRemediationEngine:.*?class AutoRemediation:", "class AutoRemediation:", content, flags=re.DOTALL)

# 2. Add _create_github_pr to AutoRemediation
new_method = '''
    def _create_github_pr(self, file_path: str, old_code: str, new_code: str, issue: str):
        """GitHub PR creator"""
        from github import Github
        import os
        token = os.getenv("GITHUB_TOKEN")
        repo_name = os.getenv("GITHUB_REPOSITORY", "paykaribazaronline/supremeai")
        if not token or not repo_name:
            logger.warning("GitHub token/repo not set. Skipping PR creation.")
            return None
        gh = Github(token)
        repo = gh.get_repo(repo_name)
        branch_name = f"auto-fix/security-patch-{os.urandom(4).hex()}"
        main_branch = repo.get_branch("main")
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=main_branch.commit.sha)

        repo.update_file(
            path=file_path,
            message=f"🛡️ Auto-Remediation: Fixed {issue}",
            content=new_code,
            sha=repo.get_contents(file_path).sha,
            branch=branch_name,
        )

        return repo.create_pull(
            title=f"🚨 Security Auto-Patch: {file_path}",
            body=f"This PR was automatically generated by SupremeAI Immune System to fix: **{issue}**.",
            head=branch_name,
            base="main",
        )
'''
# Insert it after __init__
content = content.replace("def _validate_file_path", new_method.strip() + "\n\n    def _validate_file_path")

# 3. Use _create_github_pr instead of commit_changes
content = content.replace(
    """
        # Attempt GitHub commit
        commit_message = f"🛡️ Auto-Remediation: Fixed {issue}"
        try:
            repo_url = os.getenv("GITHUB_REPOSITORY", "paykaribazaronline/supremeai")
            self.github_agent.commit_changes(
                repo_url=repo_url,
                files_to_commit=[safe_path],
                commit_message=commit_message,
                branch="main",
            )
        except RuntimeError as e:
            if "GitHub token is required" in str(e):
                logger.warning(f"GitHub token not available; patch applied locally but not committed: {e}")
            else:
                raise
""",
    """
        # Create GitHub PR
        import asyncio
        try:
            pr = await asyncio.to_thread(self._create_github_pr, safe_path, original_code, fixed_code, issue)
            if pr:
                logger.info(f"Created PR: {pr.html_url}")
        except Exception as e:
            logger.warning(f"Failed to create PR: {e}")
""",
)

# 4. Use text_helpers for markdown stripping
content = content.replace(
    """
            # Strip markdown formatting if the model returned any
            if raw_text.strip().startswith("```"):
                lines = raw_text.strip().splitlines()
                if len(lines) > 1:
                    if lines[0].startswith("```"):
                        lines = lines[1:]
                    if lines and lines[-1].startswith("```"):
                        lines = lines[:-1]
                    raw_text = "\\n".join(lines)

            return raw_text.strip()
""",
    """
            from utils.text_helpers import strip_markdown_code_block
            return strip_markdown_code_block(raw_text)
""",
)

# 5. Simplify LaunchDarkly import
content = content.replace(
    """
        ld_ai_client = None
        AICompletionConfigDefault = None
        LDMessage = None
        ModelConfig = None
        Context = None

        try:
            from ldai import AICompletionConfigDefault as _AICompletionConfigDefault
            from ldai import LDMessage as _LDMessage
            from ldai import ModelConfig as _ModelConfig
            from ldclient.context import Context as _Context

            from core.ld_client import ld_ai_client as _ld_ai_client

            AICompletionConfigDefault = _AICompletionConfigDefault
            LDMessage = _LDMessage
            ModelConfig = _ModelConfig
            Context = _Context
            ld_ai_client = _ld_ai_client
        except Exception as exc:  # noqa: BLE001
            logger.warning(f"LaunchDarkly remediation modules unavailable, using fallback path: {exc}")
""",
    """
        from core.ld_client import get_ld_ai_components
        ld_ai_client, AICompletionConfigDefault, LDMessage, ModelConfig, Context = get_ld_ai_components()
""",
)

with open(filepath, "w", encoding="utf-8") as f:
    f.write(content)
