package org.example.model;

import java.util.*;

/**
 * Phase 6 Week 7-8: Fix Variant Model
 * Represents a variation of a fix candidate for A/B testing
 * 
 * Includes:
 * - Implementation code
 * - Performance metrics  
 * - Execution results
 * - Metadata for tracking
 */
public class FixVariant {
    
    private String variantId;
    private String fixId;
    private String strategy;
    private String implementation;
    private float executionTime;
    private float successRate;
    private float regressionDetected;
    private int linesChanged;
    private String impact;
    private long createdAt;
    private Map<String, Object> metadata;
    private List<String> testResults;

    public FixVariant() {
        this.variantId = UUID.randomUUID().toString();
        this.metadata = new HashMap<>();
        this.testResults = new ArrayList<>();
        this.createdAt = System.currentTimeMillis();
    }

    public FixVariant(String fixId, String strategy) {
        this();
        this.fixId = fixId;
        this.strategy = strategy;
    }

    // ==================== Variant Strategies ====================

    public enum Strategy {
        PATTERN_MATCH("pattern-match", "Use known error patterns"),
        TEMPLATE_BASED("template-based", "Apply template for fix type"),
        AI_GENERATED("ai-generated", "Generated by AI model"),
        MANUAL_REVIEW("manual-review", "Manually reviewed/crafted"),
        HYBRID("hybrid", "Combination of strategies");

        public final String id;
        public final String description;

        Strategy(String id, String description) {
            this.id = id;
            this.description = description;
        }

        public static Strategy fromString(String id) {
            for (Strategy s : Strategy.values()) {
                if (s.id.equals(id)) {
                    return s;
                }
            }
            return MANUAL_REVIEW;
        }
    }

    // ==================== Impact Assessment ====================

    public enum Impact {
        LOW("low", "Minimal changes, low risk"),
        MEDIUM("medium", "Moderate changes"),
        HIGH("high", "Extensive changes, requires testing"),
        CRITICAL("critical", "Major architectural changes");

        public final String level;
        public final String description;

        Impact(String level, String description) {
            this.level = level;
            this.description = description;
        }

        public static Impact fromRiskLevel(int linesChanged) {
            if (linesChanged <= 5) return LOW;
            if (linesChanged <= 20) return MEDIUM;
            if (linesChanged <= 100) return HIGH;
            return CRITICAL;
        }
    }

    // ==================== A/B Testing Metrics ====================

    public static class TestMetrics {
        public float successRate;
        public float executionTime;
        public int testsRun;
        public int testsPassed;
        public int testsFailed;
        public float regressionRate;
        public List<String> failedTests;
        public long testDuration;

        public TestMetrics() {
            this.failedTests = new ArrayList<>();
        }

        public float getEffectiveness() {
            // (successRate - regressionRate) weighted by test coverage
            float coverage = (testsRun > 0) ? (testsPassed * 100.0f) / testsRun : 0;
            return Math.max(0, coverage - (regressionRate * 100));
        }

        public float getEfficiency() {
            // Score based on execution time (lower is better)
            // Normalized: 100ms baseline
            return Math.max(0, 100 - (executionTime / 10));
        }

        public float getOverallScore() {
            // Weighted: 60% effectiveness, 40% efficiency
            return (getEffectiveness() * 0.6f) + (getEfficiency() * 0.4f);
        }

        @Override
        public String toString() {
            return String.format("TestMetrics{success=%.1f%%, time=%.1fms, passed=%d/%d, regression=%.1f%%}",
                    successRate * 100, executionTime, testsPassed, testsRun, regressionRate * 100);
        }
    }

    // ==================== Performance  Scoring ====================

    public float calculateScore() {
        // Weighted scoring: success (50%), execution time (30%), no regressions (20%)
        float successScore = successRate * 50;
        float timeScore = (1 - Math.min(1, executionTime / 1000)) * 30; // Penalize slow executions
        float regressionScore = (1 - regressionDetected) * 20;

        return Math.max(0, Math.min(100, successScore + timeScore + regressionScore));
    }

    public boolean isBetterThan(FixVariant other) {
        return this.calculateScore() > other.calculateScore();
    }

    public Map<String, Float> getScoreBreakdown() {
        Map<String, Float> breakdown = new HashMap<>();
        breakdown.put("success", successRate * 50);
        breakdown.put("time", (1 - Math.min(1, executionTime / 1000)) * 30);
        breakdown.put("regression", (1 - regressionDetected) * 20);
        breakdown.put("total", calculateScore());
        return breakdown;
    }

    // ==================== Comparison Methods ====================

    public String compareWith(FixVariant other) {
        StringBuilder comparison = new StringBuilder();
        
        float diff = this.calculateScore() - other.calculateScore();
        comparison.append(String.format("Score difference: %.1f\n", diff));
        
        if (this.successRate > other.successRate) {
            comparison.append(String.format("This variant has higher success rate: %.1f%% vs %.1f%%\n",
                    this.successRate * 100, other.successRate * 100));
        }
        
        if (this.executionTime < other.executionTime) {
            comparison.append(String.format("This variant executes faster: %.1fms vs %.1fms\n",
                    this.executionTime, other.executionTime));
        }
        
        if (this.regressionDetected < other.regressionDetected) {
            comparison.append(String.format("This variant has lower regression: %.1f%% vs %.1f%%\n",
                    this.regressionDetected * 100, other.regressionDetected * 100));
        }

        return comparison.toString();
    }

    // ==================== Getters and Setters ====================

    public String getVariantId() { return variantId; }
    public void setVariantId(String variantId) { this.variantId = variantId; }

    public String getFixId() { return fixId; }
    public void setFixId(String fixId) { this.fixId = fixId; }

    public String getStrategy() { return strategy; }
    public void setStrategy(String strategy) { this.strategy = strategy; }

    public String getImplementation() { return implementation; }
    public void setImplementation(String implementation) { this.implementation = implementation; }

    public float getExecutionTime() { return executionTime; }
    public void setExecutionTime(float executionTime) { this.executionTime = executionTime; }

    public float getSuccessRate() { return successRate; }
    public void setSuccessRate(float successRate) { this.successRate = Math.max(0, Math.min(1, successRate)); }

    public float getRegressionDetected() { return regressionDetected; }
    public void setRegressionDetected(float regressionDetected) { 
        this.regressionDetected = Math.max(0, Math.min(1, regressionDetected)); 
    }

    public int getLinesChanged() { return linesChanged; }
    public void setLinesChanged(int linesChanged) { this.linesChanged = linesChanged; }

    public String getImpact() { return impact; }
    public void setImpact(String impact) { this.impact = impact; }

    public long getCreatedAt() { return createdAt; }
    public void setCreatedAt(long createdAt) { this.createdAt = createdAt; }

    public Map<String, Object> getMetadata() { return metadata; }
    public void setMetadata(Map<String, Object> metadata) { this.metadata = metadata; }

    public List<String> getTestResults() { return testResults; }
    public void setTestResults(List<String> testResults) { this.testResults = testResults; }
    public void addTestResult(String result) { this.testResults.add(result); }

    @Override
    public String toString() {
        return String.format("FixVariant{id=%s, strategy=%s, score=%.1f, success=%.1f%%, time=%.1fms}",
                variantId, strategy, calculateScore(), successRate * 100, executionTime);
    }

    public Map<String, Object> toMap() {
        Map<String, Object> map = new HashMap<>();
        map.put("variantId", variantId);
        map.put("fixId", fixId);
        map.put("strategy", strategy);
        map.put("implementation", implementation);
        map.put("executionTime", executionTime);
        map.put("successRate", successRate);
        map.put("regressionDetected", regressionDetected);
        map.put("linesChanged", linesChanged);
        map.put("impact", impact);
        map.put("score", calculateScore());
        map.put("scoreBreakdown", getScoreBreakdown());
        map.put("createdAt", createdAt);
        map.put("testResults", testResults);
        return map;
    }
}
