// Auto-generated by SupremeAI Type Generator
// Source: schemas.skill_manifest.SkillManifest

export interface SkillManifest {
  /** ইউনিক স্কিল আইডেন্টিফায়ার (slug) */
  skillId: null;
  /** স্কিলের মানব-পাঠ্য নাম */
  name: null;
  /** FastAPI বা এজেন্ট রাউটার যার মাধ্যমে ম্যাচিং করবে */
  description: null;
  version?: null;
  /** ভেরিফায়েড MCP বা গিটহাব রিপোজিটরি উৎস */
  sourceUrl: null;
  /** SHA-256 কোড ইন্টিগ্রিটি হ্যাশ */
  checksum: null;
  status?: null;
  permissions?: null;
  governance?: any;
  usageCount?: null;
  failureCount?: null;
  lastUsedAt?: any;
  createdAt?: null;
  expiresAt?: any;
}
