// Auto-generated by SupremeAI Type Generator
// Source: schemas.skill_manifest.SkillPermissions

export interface SkillPermissions {
  /** স্কিলটি ইন্টারনেট অ্যাক্সেস করতে পারবে কিনা */
  allowNetwork?: null;
  /** নেটওয়ার্ক ট্রাস্টেড ওরিজিন ডোমেইন লিস্ট */
  allowedDomains?: null[];
  /** লোকাল ফাইলে রাইট করার অনুমতি */
  allowFilesystemWrite?: null;
  /** কাজ করার জন্য প্রয়োজনীয় পরিবেশ ভ্যারিয়েবল */
  requiredEnvVars?: null[];
}
