// Auto-generated by SupremeAI Type Generator
// Source: schemas.skill_manifest.SkillGovernance

/** Runtime contract for a published skill.

    The defaults deliberately deny data, tools, and execution approvals.  A skill
    must opt in to every capability in its manifest instead of inheriting broad
    platform access. */
export interface SkillGovernance {
  owner: null;
  allowedData?: null[];
  allowedRoles?: null[];
  toolsAllowed?: null[];
  humanApprovalPoints?: Record<null, null>;
  successMetrics?: Record<null, null>;
  evaluationTests?: null[];
  budget?: Record<null, null>;
  auditLogging?: null[];
}
