{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-configuration-processor",
    "version": "3.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.2.3.jar",
          "url": "spring-boot-configuration-processor-3.2.3.jar",
          "size": 121987,
          "sha512": "43359976e6b5987d41b27909c6a16fb434266c34db61cc4fb4f62decf36856e0bec0601936408d974905ceb21b638a3031db16595321c78109cda41005a94381",
          "sha256": "1da289cc729a99ead2c9b587178292d245c34b64e2c4fa394b851047edfa318e",
          "sha1": "ddfb951196f104bf6c5d2f2b4bd86108ff81abcd",
          "md5": "fe18ebe82d7672f7e29b125993e7f03f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.2.3.jar",
          "url": "spring-boot-configuration-processor-3.2.3.jar",
          "size": 121987,
          "sha512": "43359976e6b5987d41b27909c6a16fb434266c34db61cc4fb4f62decf36856e0bec0601936408d974905ceb21b638a3031db16595321c78109cda41005a94381",
          "sha256": "1da289cc729a99ead2c9b587178292d245c34b64e2c4fa394b851047edfa318e",
          "sha1": "ddfb951196f104bf6c5d2f2b4bd86108ff81abcd",
          "md5": "fe18ebe82d7672f7e29b125993e7f03f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.2.3-javadoc.jar",
          "url": "spring-boot-configuration-processor-3.2.3-javadoc.jar",
          "size": 185324,
          "sha512": "d719e86b25c826ab3d7e13e1fd408da5d030ac4cd020ca5ae10249af1d327b24b40f974a3f445aaba1f94bec2f6a10c81f8dfc8fb0e8d0a09b7fa26c6a9c1e5a",
          "sha256": "c83b86eae4f6e90825e4654b2b8deb3b24f181c15c2692dbe3513c19130598f8",
          "sha1": "3047b40da5104cfcdeb3239d0065737c4fa21e47",
          "md5": "0fe6c52e689e62dea918c0eebab8fbaa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.2.3-sources.jar",
          "url": "spring-boot-configuration-processor-3.2.3-sources.jar",
          "size": 80055,
          "sha512": "13cdceb8ac6d1775b431419394861646c587192ebf4dc05a735c23fb9d32bcfb315ee4bc68f5fa88a14845aaa8c03b004e9cea2abd22535d3009b2e2f21516f9",
          "sha256": "97998d2b1193c5d5b0354d457e9052f1bb3c56dd346d3d448c51d401a76cbfcb",
          "sha1": "27e43c2e92876ecbc4fc4f71f653ad10570bc03d",
          "md5": "478ec9d8ac044e2b12417a45cf1b120b"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.2.3.jar",
          "url": "spring-boot-configuration-processor-3.2.3.jar",
          "size": 121987,
          "sha512": "43359976e6b5987d41b27909c6a16fb434266c34db61cc4fb4f62decf36856e0bec0601936408d974905ceb21b638a3031db16595321c78109cda41005a94381",
          "sha256": "1da289cc729a99ead2c9b587178292d245c34b64e2c4fa394b851047edfa318e",
          "sha1": "ddfb951196f104bf6c5d2f2b4bd86108ff81abcd",
          "md5": "fe18ebe82d7672f7e29b125993e7f03f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-configuration-processor-maven-optional",
          "version": "3.2.3"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.2.3.jar",
          "url": "spring-boot-configuration-processor-3.2.3.jar",
          "size": 121987,
          "sha512": "43359976e6b5987d41b27909c6a16fb434266c34db61cc4fb4f62decf36856e0bec0601936408d974905ceb21b638a3031db16595321c78109cda41005a94381",
          "sha256": "1da289cc729a99ead2c9b587178292d245c34b64e2c4fa394b851047edfa318e",
          "sha1": "ddfb951196f104bf6c5d2f2b4bd86108ff81abcd",
          "md5": "fe18ebe82d7672f7e29b125993e7f03f"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-configuration-processor-maven-optional",
          "version": "3.2.3"
        }
      ]
    }
  ]
}
