{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.guava",
    "module": "guava",
    "version": "32.1.3-jre",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.4",
      "buildId": "Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)"
    }
  },
  "variants": [
    {
      "name": "jreApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": "8",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "failureaccess",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "9999.0-empty-to-avoid-conflict-with-guava"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.37.0"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.21.1"
          }
        },
        {
          "group": "com.google.j2objc",
          "module": "j2objc-annotations",
          "version": {
            "requires": "2.8"
          }
        }
      ],
      "files": [
        {
          "name": "guava-32.1.3-jre.jar",
          "url": "guava-32.1.3-jre.jar"
        }
      ],
      "capabilities": [
        {
          "group": "com.google.guava",
          "name": "guava",
          "version": "32.1.3-jre"
        },
        {
          "group": "com.google.collections",
          "name": "google-collections",
          "version": "32.1.3-jre"
        }
      ]
    },
    {
      "name": "jreRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": "8",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "failureaccess",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "9999.0-empty-to-avoid-conflict-with-guava"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.37.0"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "guava-32.1.3-jre.jar",
          "url": "guava-32.1.3-jre.jar"
        }
      ],
      "capabilities": [
        {
          "group": "com.google.guava",
          "name": "guava",
          "version": "32.1.3-jre"
        },
        {
          "group": "com.google.collections",
          "name": "google-collections",
          "version": "32.1.3-jre"
        }
      ]
    },
    {
      "name": "androidApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": "8",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "failureaccess",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "9999.0-empty-to-avoid-conflict-with-guava"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.37.0"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.21.1"
          }
        },
        {
          "group": "com.google.j2objc",
          "module": "j2objc-annotations",
          "version": {
            "requires": "2.8"
          }
        }
      ],
      "files": [
        {
          "name": "guava-32.1.3-android.jar",
          "url": "../32.1.3-android/guava-32.1.3-android.jar"
        }
      ],
      "capabilities": [
        {
          "group": "com.google.guava",
          "name": "guava",
          "version": "32.1.3-jre"
        },
        {
          "group": "com.google.collections",
          "name": "google-collections",
          "version": "32.1.3-jre"
        }
      ]
    },
    {
      "name": "androidRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": "8",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "failureaccess",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "9999.0-empty-to-avoid-conflict-with-guava"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.37.0"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "guava-32.1.3-android.jar",
          "url": "../32.1.3-android/guava-32.1.3-android.jar"
        }
      ],
      "capabilities": [
        {
          "group": "com.google.guava",
          "name": "guava",
          "version": "32.1.3-jre"
        },
        {
          "group": "com.google.collections",
          "name": "google-collections",
          "version": "32.1.3-jre"
        }
      ]
    }
  ]
}
