#!/usr/bin/env python3
"""Build a compact AI-ready project context pack without dumping the whole repo."""
from __future__ import annotations
import argparse, os, json, re
from pathlib import Path
EXCLUDED={'.git','node_modules','.venv','venv','dist','build','coverage','.next','.turbo','target','__pycache__','.pytest_cache'}
IMPORTANT_NAMES={'readme.md','agents.md','claude.md','cursor.md','contributing.md','security.md','docker-compose.yml','docker-compose.yaml','package.json','pyproject.toml','requirements.txt','pnpm-workspace.yaml','turbo.json','vercel.json','render.yaml'}
KEYWORDS=('router','gateway','auth','config','settings','main','app','server','api','service','worker','queue','cache','database','schema','model','provider','test','workflow','deploy')
EXTS={'.py','.ts','.tsx','.js','.jsx','.json','.yaml','.yml','.toml','.md','.sql'}
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('root',nargs='?',default='.'); ap.add_argument('--out',default='reports/context-pack.md'); ap.add_argument('--max-files',type=int,default=80); ap.add_argument('--max-chars',type=int,default=180000); args=ap.parse_args(); root=Path(args.root).resolve(); candidates=[]
 for base,ds,ns in os.walk(root):
  ds[:]=[d for d in ds if d not in EXCLUDED]
  for n in ns:
   p=Path(base)/n
   if not p.is_file() or p.suffix.lower() not in EXTS: continue
   r=str(p.relative_to(root)).replace('\\','/'); score=0; low=n.lower()
   if low in IMPORTANT_NAMES: score+=100
   score+=sum(8 for k in KEYWORDS if k in low or k in r.lower())
   try: score+=min(20,int(p.stat().st_size/2000))
   except OSError: pass
   candidates.append((score,r,p))
 candidates.sort(reverse=True); selected=candidates[:args.max_files]
 lines=[f'# AI Context Pack: {root.name}','', 'Generated by SupremeAI Context Packager. This is a navigation-oriented summary, not a source-of-truth replacement.','', '## Project tree (selected)','']
 for s,r,p in selected: lines.append(f'- `{r}` (relevance={s})')
 lines += ['', '## Key file excerpts','']
 used=0
 for s,r,p in selected:
  try:t=p.read_text('utf-8','ignore')
  except OSError: continue
  excerpt=t if len(t)<=3500 else t[:3500]+'\n... [truncated]'
  if used+len(excerpt)>args.max_chars: break
  lines += [f'### `{r}`','', '```', excerpt, '```','']; used+=len(excerpt)
 out=Path(args.out); out.parent.mkdir(parents=True,exist_ok=True); out.write_text('\n'.join(lines),encoding='utf-8'); print(f'wrote {out} ({used} chars)')
if __name__=='__main__': main()
