package org.example.service;

import java.io.IOException;
import java.nio.file.*;
import java.util.HashMap;
import java.util.Map;

public class TemplateManager {
    private final Path templatePath;
    private final FileOrchestrator fileOrchestrator;
    private final Map<String, String[]> templateStructures = new HashMap<>();

    public TemplateManager(String templateDir, FileOrchestrator fileOrchestrator) {
        this.templatePath = Paths.get(templateDir);
        this.fileOrchestrator = fileOrchestrator;
        initializeDefaultStructures();
    }

    private void initializeDefaultStructures() {
        // Define basic folders for different project types
        templateStructures.put("FLUTTER", new String[]{"lib", "test", "assets", "android", "ios"});
        templateStructures.put("REACT", new String[]{"src", "public", "node_modules", "src/components", "src/hooks"});
        templateStructures.put("NODEJS", new String[]{"src", "tests", "config", "src/models", "src/routes"});
    }

    /**
     * Initializes a project folder with the base structure of a template.
     */
    public void initializeProject(String projectId, String templateType) throws IOException {
        System.out.println("📂 [TEMPLATE] Initializing " + templateType + " project for: " + projectId);
        
        String[] folders = templateStructures.getOrDefault(templateType.toUpperCase(), new String[]{"src"});
        
        for (String folder : folders) {
            fileOrchestrator.writeFile(projectId, folder + "/.keep", ""); // Create folder with placeholder
        }
        
        // Add a basic README
        String readmeContent = "# Project: " + projectId + "\nGenerated by SupremeAI\nTemplate: " + templateType;
        fileOrchestrator.writeFile(projectId, "README.md", readmeContent);
        
        System.out.println("✅ [TEMPLATE] Structure ready for " + templateType);
    }
}
