# backend/evolution/__init__.py
"""SupremeAI Evolution Package (Backward Compatibility Facade).

Re-exports all evolution research modules and core evolution engines from
the single source of truth: `core.evolution`.
"""

from __future__ import annotations

# Re-export from core.evolution
from core.evolution import (
    # Core Evolution
    AgentBreeder,
    AutoSkillCreator,
    DailyLearner,
    EvolutionEngine,
    EvolutionReactAgent,
    FitnessEngine,
    PerformanceOracle,
    SelfEvolutionAgent,
    SelfUpdater,
    SkillGraph,
    # Digital Twin
    DigitalTwinWorldModel,
    ImpactSimulator,
    RemediationEngine,
    SystemTopologyMapper,
    get_digital_twin_model,
    initialize_digital_twin,
    # Continual Learning
    EWC,
    EWCConfig,
    EWCTrainer,
    OnlineEWC,
    # Adversarial Defense
    AdversarialDefenseSystem,
    AdversarialTrainer,
    AttackType,
    DefenseConfig,
    # Neural Symbolic
    MathematicalReasoningEngine,
    NeuralSymbolicConfig,
    NeuralSymbolicIntegrator,
    SymbolicExpression,
    SymbolicReasoner,
    # Federated Learning
    AggregationStrategy,
    FederatedClient,
    FederatedConfig,
    FederatedCoordinator,
    FederatedRoundResult,
    ModelWeights,
    # Theory of Mind
    AgentPerspective,
    CognitiveState,
    InteractionRecord,
    PerspectiveTracker,
    TheoryOfMindConfig,
    TheoryOfMindEngine,
    # Temporal Abstraction
    HierarchicalPlanner,
    MacroAction,
    Option,
    OptionCritic,
    TemporalAbstractionConfig,
    TemporalAbstractionEngine,
    TemporalState,
    TimeHorizon,
)

__all__ = [
    "AgentBreeder",
    "AutoSkillCreator",
    "DailyLearner",
    "EvolutionEngine",
    "EvolutionReactAgent",
    "FitnessEngine",
    "PerformanceOracle",
    "SelfEvolutionAgent",
    "SelfUpdater",
    "SkillGraph",
    "DigitalTwinWorldModel",
    "ImpactSimulator",
    "RemediationEngine",
    "SystemTopologyMapper",
    "get_digital_twin_model",
    "initialize_digital_twin",
    "EWC",
    "EWCConfig",
    "EWCTrainer",
    "OnlineEWC",
    "AdversarialDefenseSystem",
    "AdversarialTrainer",
    "AttackType",
    "DefenseConfig",
    "MathematicalReasoningEngine",
    "NeuralSymbolicConfig",
    "NeuralSymbolicIntegrator",
    "SymbolicExpression",
    "SymbolicReasoner",
    "AggregationStrategy",
    "FederatedClient",
    "FederatedConfig",
    "FederatedCoordinator",
    "FederatedRoundResult",
    "ModelWeights",
    "AgentPerspective",
    "CognitiveState",
    "InteractionRecord",
    "PerspectiveTracker",
    "TheoryOfMindConfig",
    "TheoryOfMindEngine",
    "HierarchicalPlanner",
    "MacroAction",
    "Option",
    "OptionCritic",
    "TemporalAbstractionConfig",
    "TemporalAbstractionEngine",
    "TemporalState",
    "TimeHorizon",
]
