import React, { useState } from 'react';
import { Card, Input, Button, Progress, List, Tag, Typography, Space, Divider, message } from 'antd';
import { RocketOutlined, CodeOutlined, RobotOutlined, CheckCircleOutlined } from '@ant-design/icons';
import { authUtils } from '../lib/authUtils';

const { TextArea } = Input;
const { Title, Text, Paragraph } = Typography;

const ProjectGenerator: React.FC = () => {
    const [requirement, setRequirement] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);
    const [progress, setProgress] = useState(0);
    const [steps, setSteps] = useState<any[]>([]);
    const [result, setResult] = useState<any>(null);

    const generateProject = async () => {
        if (!requirement.trim()) {
            message.warning('Please enter your project requirements');
            return;
        }

        setIsGenerating(true);
        setProgress(10);
        setSteps([
            { title: 'Requirement Analysis', status: 'processing', icon: <RobotOutlined /> },
        ]);

        try {
            const token = authUtils.getToken();
            const response = await fetch('/api/orchestrate/requirement', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    ...(token ? { Authorization: `Bearer ${token}` } : {}),
                },
                body: JSON.stringify({ requirement }),
            });

            if (!response.ok) throw new Error('Generation failed');

            const data = await response.json();
            
            // Simulate steps
            setProgress(40);
            setSteps(prev => [
                { ...prev[0], status: 'finish' },
                { title: 'Architecture Design', status: 'processing', icon: <CodeOutlined /> }
            ]);

            setTimeout(() => {
                setProgress(70);
                setSteps(prev => [
                    ...prev.slice(0, 1),
                    { ...prev[1], status: 'finish' },
                    { title: 'Code Generation (Gemini)', status: 'processing', icon: <RobotOutlined /> }
                ]);
            }, 2000);

            setTimeout(() => {
                setProgress(100);
                setSteps(prev => [
                    ...prev.slice(0, 2),
                    { ...prev[2], status: 'finish' },
                    { title: 'Project Ready', status: 'finish', icon: <CheckCircleOutlined /> }
                ]);
                setResult(data);
                setIsGenerating(false);
                message.success('Project successfully generated by Google SupremeAI!');
            }, 4000);

        } catch (err: any) {
            message.error(err.message);
            setIsGenerating(false);
        }
    };

    return (
        <Card 
            title={
                <Space>
                    <RocketOutlined style={{ color: '#4285F4' }} />
                    <span>Google SupremeAI Project Generator</span>
                </Space>
            }
            bordered={false}
            style={{ borderRadius: '16px', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)' }}
        >
            <div style={{ marginBottom: '24px' }}>
                <Paragraph>
                    Describe the Android app you want to build. Our AI agents (powered by Gemini) will design the architecture, generate the code, and set up the infrastructure.
                </Paragraph>
                <TextArea
                    rows={4}
                    placeholder="e.g., Build a real-time food delivery app with user authentication, maps integration, and payment gateway."
                    value={requirement}
                    onChange={(e) => setRequirement(e.target.value)}
                    disabled={isGenerating}
                    style={{ borderRadius: '12px' }}
                />
                <Button 
                    type="primary" 
                    icon={<RocketOutlined />} 
                    size="large"
                    onClick={generateProject}
                    loading={isGenerating}
                    style={{ marginTop: '16px', width: '100%', borderRadius: '12px', height: '48px', background: '#4285F4' }}
                >
                    {isGenerating ? 'AI Agents are Working...' : 'Generate AI Project'}
                </Button>
            </div>

            {isGenerating && (
                <div style={{ marginTop: '32px' }}>
                    <Progress percent={progress} status="active" strokeColor={{ '0%': '#4285F4', '100%': '#34A853' }} />
                    <List
                        size="small"
                        dataSource={steps}
                        renderItem={item => (
                            <List.Item>
                                <Space>
                                    {item.icon}
                                    <Text delete={item.status === 'finish'}>{item.title}</Text>
                                    {item.status === 'finish' && <CheckCircleOutlined style={{ color: '#34A853' }} />}
                                </Space>
                            </List.Item>
                        )}
                        style={{ marginTop: '16px' }}
                    />
                </div>
            )}

            {result && !isGenerating && (
                <div style={{ marginTop: '32px' }}>
                    <Divider>Generation Result</Divider>
                    <Card size="small" style={{ background: '#F9FAFB', borderRadius: '12px' }}>
                        <Title level={5}>Detected Tasks:</Title>
                        <Space wrap>
                            {result.tasks?.map((task: any, idx: number) => (
                                <Tag key={idx} color="blue">{task}</Tag>
                            )) || <Text type="secondary">Consolidating architecture...</Text>}
                        </Space>
                        <div style={{ marginTop: '16px' }}>
                            <Button type="link" icon={<CodeOutlined />}>Open in Code Editor</Button>
                            <Button type="link" icon={<RocketOutlined />}>Preview in Simulator</Button>
                        </div>
                    </Card>
                </div>
            )}
        </Card>
    );
};

export default ProjectGenerator;
