import { OpenAI } from 'openai';
import * as vscode from 'vscode';

export interface CodeSuggestion {
  id: string;
  type: 'completion' | 'refactor' | 'fix' | 'explanation';
  title: string;
  description: string;
  code: string;
  explanation: string;
  confidence: number;
  language: string;
  context: vscode.Position | null;
}

export class AIService {
  private openai: OpenAI | null = null;
  private isEnabled: boolean;

  constructor() {
    this.isEnabled = false;
    this.initializeClient();
  }

  private initializeClient(): void {
    const config = vscode.workspace.getConfiguration('supremeai');
    const apiKey = config.get<string>('aiApiKey', '');
    
    if (apiKey) {
      this.openai = new OpenAI({ apiKey });
      this.isEnabled = true;
    }
  }

  async generateCodeCompletion(
    prompt: string,
    language: string,
    context?: string
  ): Promise<CodeSuggestion | null> {
    if (!this.openai || !this.isEnabled) {
      return this.getFallbackSuggestion(prompt, language);
    }

    try {
      const config = vscode.workspace.getConfiguration('supremeai');
      const modelName = config.get<string>('aiModel', 'supreme-large');

      const response = await this.openai.chat.completions.create({
        model: modelName,
        messages: [
          {
            role: 'system',
            content: this.getSystemPrompt(language, context),
          },
          { role: 'user', content: prompt },
        ],
        temperature: 0.3,
        max_tokens: 500,
      });

      const choice = response.choices[0]?.message?.content;
      if (!choice) { return null; }

      return {
        id: `sugg_${Date.now()}`,
        type: 'completion',
        title: 'AI Code Suggestion',
        description: 'Generated by SupremeAI',
        code: choice,
        explanation: 'AI generated code to complete your implementation',
        confidence: 0.9,
        language,
        context: null,
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error('[SupremeAI] AI completion error:', message);
      return this.getFallbackSuggestion(prompt, language);
    }
  }

  async explainCode(code: string, language: string): Promise<string> {
    if (!this.openai || !this.isEnabled) {
      return this.fallbackExplain(code, language);
    }

    try {
      const config = vscode.workspace.getConfiguration('supremeai');
      const modelName = config.get<string>('aiModel', 'supreme-large');

      const response = await this.openai.chat.completions.create({
        model: modelName,
        messages: [
          {
            role: 'system',
            content: `Explain the following ${language} code in simple terms. Focus on what the code does and how it works.`,
          },
          { role: 'user', content: code },
        ],
        temperature: 0.2,
        max_tokens: 300,
      });

      return response.choices[0]?.message?.content || 'Unable to explain code';
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error('[SupremeAI] Code explanation error:', message);
      return this.fallbackExplain(code, language);
    }
  }

  async suggestRefactor(code: string, language: string): Promise<CodeSuggestion | null> {
    if (!this.openai || !this.isEnabled) {
      return null;
    }

    try {
      const config = vscode.workspace.getConfiguration('supremeai');
      const modelName = config.get<string>('aiModel', 'supreme-large');

      const response = await this.openai.chat.completions.create({
        model: modelName,
        messages: [
          {
            role: 'system',
            content: `Provide refactoring suggestions for the following ${language} code. Return a JSON with: suggestions (array of {description, code, improvement})`,
          },
          { role: 'user', content: code },
        ],
        temperature: 0.4,
        max_tokens: 800,
      });

      const content = response.choices[0]?.message?.content;
      if (!content) { return null; }

      const parsed = JSON.parse(content);
      return {
        id: `refactor_${Date.now()}`,
        type: 'refactor',
        title: 'Refactoring Suggestions',
        description: parsed.suggestions?.[0]?.description || 'Code improvement suggestions',
        code: parsed.suggestions?.[0]?.code || code,
        explanation: parsed.suggestions?.[0]?.improvement || 'Improved code structure',
        confidence: 0.85,
        language,
        context: null,
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error('[SupremeAI] Refactor suggestion error:', message);
      return null;
    }
  }

  private getSystemPrompt(language: string, context?: string): string {
    return `You are SupremeAI, an AI coding assistant for ${language}. ${context || ''} 
You help developers by providing code suggestions, explanations, and improvements.
Always respond with working, production-ready code.`;
  }

  private getFallbackSuggestion(prompt: string, language: string): CodeSuggestion | null {
    return {
      id: `fallback_${Date.now()}`,
      type: 'completion',
      title: 'Code Suggestion',
      description: 'Basic suggestion (AI unavailable)',
      code: `// TODO: Implement based on: ${prompt.slice(0, 100)}...`,
      explanation: 'AI service not configured. Please add AI API key in settings.',
      confidence: 0.3,
      language,
      context: null,
    };
  }

  private fallbackExplain(code: string, language: string): string {
    return `AI explanation unavailable. This appears to be ${language} code with ${code.split('\n').length} lines.
Configure SupremeAI with an AI API key for detailed explanations.`;
  }

  updateConfiguration(): void {
    this.initializeClient();
  }

  isAIEnabled(): boolean {
    return this.isEnabled;
  }
}

let aiServiceInstance: AIService | null = null;

export function getAIService(): AIService {
  if (!aiServiceInstance) {
    aiServiceInstance = new AIService();
  }
  return aiServiceInstance;
}

export function setAIService(service: AIService): void {
  aiServiceInstance = service;
}