import * as vscode from 'vscode';
import { getSupremeAIService } from '../services/SupremeAIService';

export interface CodeSuggestion {
  id: string;
  type: 'completion' | 'refactor' | 'fix' | 'explanation';
  title: string;
  description: string;
  code: string;
  explanation: string;
  confidence: number;
  language: string;
  context: vscode.Position | null;
}

export class AIService {
  private isEnabled: boolean;

  constructor() {
    // Thin Client নীতি: ক্লায়েন্ট-সাইডে কোনো তৃতীয়-পক্ষ API key নেই।
    // সকল LLM অর্কেস্ট্রেশন SupremeAI ব্যাকএন্ডের মাধ্যমে হয়।
    this.isEnabled = true;
  }

  async generateCodeCompletion(
    prompt: string,
    language: string,
    context?: string
  ): Promise<CodeSuggestion | null> {
    try {
      const fullPrompt = this.getSystemPrompt(language, context) + '\n\nTask:\n' + prompt;
      const content = await this.resolveViaBackend(fullPrompt, language);
      if (!content) { return this.getFallbackSuggestion(prompt, language); }

      return {
        id: `sugg_${Date.now()}`,
        type: 'completion',
        title: 'AI Code Suggestion',
        description: 'Generated by SupremeAI backend',
        code: content,
        explanation: 'AI generated code via SupremeAI backend',
        confidence: 0.9,
        language,
        context: null,
      };
    } catch (error) {
      return this.getFallbackSuggestion(prompt, language);
    }
  }

  async explainCode(code: string, language: string): Promise<string> {
    const prompt = `Explain the following ${language} code in simple terms. Focus on what the code does and how it works.\n\n\`\`\`${language}\n${code}\n\`\`\``;
    const content = await this.resolveViaBackend(prompt, language);
    return content || this.fallbackExplain(code, language);
  }

  async suggestRefactor(code: string, language: string): Promise<CodeSuggestion | null> {
    const prompt = `Provide refactoring suggestions for the following ${language} code. Return a JSON with: suggestions (array of {description, code, improvement}):\n\n\`\`\`${language}\n${code}\n\`\`\``;
    const content = await this.resolveViaBackend(prompt, language);
    if (!content) { return null; }

    let parsed: any;
    try {
      parsed = JSON.parse(content);
    } catch (err) {
      console.error('[SupremeAI] Failed to parse AI response:', err);
      return null;
    }
    // Basic validation for the parsed content
    if (!parsed.suggestions || !Array.isArray(parsed.suggestions) || parsed.suggestions.length === 0) {
      console.error('[SupremeAI] Refactor suggestion response is not in the expected format:', content);
      return null;
    }
    return {
      id: `refactor_${Date.now()}`,
      type: 'refactor',
      title: 'Refactoring Suggestions',
      description: parsed.suggestions?.[0]?.description || 'Code improvement suggestions',
      code: parsed.suggestions?.[0]?.code || code,
      explanation: parsed.suggestions?.[0]?.improvement || 'Improved code structure',
      confidence: 0.85,
      language,
      context: null,
    };
  }

  private getSystemPrompt(language: string, context?: string): string {
    return `You are SupremeAI, an AI coding assistant for ${language}. ${context || ''}
You help developers by providing code suggestions, explanations, and improvements.
Always respond with working, production-ready code.`;
  }

  private getFallbackSuggestion(prompt: string, language: string): CodeSuggestion | null {
    return {
      id: `fallback_${Date.now()}`,
      type: 'completion',
      title: 'Code Suggestion',
      description: 'Basic suggestion (AI unavailable)',
      code: `// TODO: Implement based on: ${prompt.slice(0, 100)}...`,
      explanation: 'AI service not configured. Please add AI API key in settings.',
      confidence: 0.3,
      language,
      context: null,
    };
  }

  private fallbackExplain(code: string, language: string): string {
    return `AI explanation unavailable. This appears to be ${language} code with ${code.split('\n').length} lines.
Configure SupremeAI with an AI API key for detailed explanations.`;
  }

  updateConfiguration(): void {
    // Thin Client: ক্লায়েন্ট-সাইডে কোনো API key কনফিগ নেই, তাই renewed initialization প্রয়োজন নেই।
  }

  isAIEnabled(): boolean {
    return this.isEnabled;
  }

  /**
   * ব্যাকএন্ড (SupremeAI) এর মাধ্যমে LLM রিকোয়েস্ট রাউট করে। ব্যাকএন্ডই LLM অর্কেস্ট্রেট করে,
   * তাই ক্লায়েন্ট-সাইডে কোনো তৃতীয়-পক্ষ API key পাঠানো হয় না (Thin Client + Brand Exclusivity)।
   */
  private async resolveViaBackend(prompt: string, language: string): Promise<string | null> {
    try {
      const service = getSupremeAIService();
      const response = await service.sendChatMessage({
        message: prompt,
        sessionId: service.getSessionId(),
        messages: [],
        context: { source: 'vscode', timestamp: new Date().toISOString() },
      });
      const content = response.response || response.message;
      return content || null;
    } catch (error: any) {
      console.error(`[SupremeAI] Backend resolve error: ${error.message}`);
      return null;
    }
  }
}

let aiServiceInstance: AIService | null = null;

export function getAIService(): AIService {
  if (!aiServiceInstance) {
    aiServiceInstance = new AIService();
  }
  return aiServiceInstance;
}

export function setAIService(service: AIService): void {
  aiServiceInstance = service;
}
