// ============================================================================
// file >> CodeGenerationService.ts
// project >> SupremeAI 2.0
// purpose >> Business service
// module >> tools
// ============================================================================
import { getSupremeAIService } from '../services/SupremeAIService';

export interface CodeSuggestionItem {
  description: string;
  code: string;
  improvement: string;
}

export class CodeGenerationService {
  private aiService = getAIService();
  private backendService = getSupremeAIService();

  async generateFunction(
    functionName: string,
    parameters: string,
    returnType: string,
    language: string
  ): Promise<CodeSuggestion | null> {
    const prompt = `Generate a ${language} function named ${functionName} with parameters (${parameters}) returning ${returnType}. Provide only the function code.`;
    return this._resolve(prompt, language);
  }

  async generateClass(
    className: string,
    methods: string[],
    language: string
  ): Promise<CodeSuggestion | null> {
    const methodsStr = methods.join(', ');
    const prompt = `Generate a ${language} class named ${className} with methods: ${methodsStr}. Include constructor and proper encapsulation.`;
    return this._resolve(prompt, language);
  }

  async generateTest(
    functionName: string,
    language: string
  ): Promise<CodeSuggestion | null> {
    const prompt = `Generate unit tests for ${functionName} function in ${language}. Include edge cases.`;
    return this._resolve(prompt, language);
  }

  async generateDocumentation(
    code: string,
    language: string
  ): Promise<string> {
    const prompt = `Generate JSDoc/TSDoc documentation for this ${language} code:\n${code}`;
    const result = await this._resolve(prompt, language);
    return result?.code || 'Documentation generation unavailable';
  }

  async explainError(
    error: string,
    code: string,
    language: string
  ): Promise<string> {
    const prompt = `Explain this ${language} error and provide a fix:\nError: ${error}\nCode:\n${code}`;
    const result = await this._resolve(prompt, language);
    return result?.code || this.aiService.explainCode(code, language);
  }

  async generateFromComment(
    comment: string,
    language: string
  ): Promise<CodeSuggestion | null> {
    const prompt = `Convert this comment into working ${language} code:\n"${comment}"`;
    return this._resolve(prompt, language);
  }

  async learnFromEdit(
    originalCode: string,
    editedCode: string,
    language: string,
    filePath: string
  ): Promise<void> {
    console.log('[SupremeAI] Learning from edit:', filePath);
  }

  private async _resolve(prompt: string, language: string): Promise<CodeSuggestion | null> {
    try {
      const response = await this.backendService.sendChatMessage({
        message: prompt,
        sessionId: this.backendService.getSessionId(),
        messages: [],
        context: { source: 'vscode', timestamp: new Date().toISOString() },
      });
      return {
        id: `vscode_gen_${Date.now()}`,
        type: 'completion',
        title: 'AI Code Generation',
        description: 'Generated by SupremeAI backend',
        code: response.response || response.message || '',
        explanation: 'AI generated code from backend',
        confidence: 0.9,
        language,
        context: null,
      };
    } catch {
      return this.aiService.generateCodeCompletion(prompt, language);
    }
  }
}

let codeGenerationInstance: CodeGenerationService | null = null;

export function getCodeGenerationService(): CodeGenerationService {
  if (!codeGenerationInstance) {
    codeGenerationInstance = new CodeGenerationService();
  }
  return codeGenerationInstance;
}

export function setCodeGenerationService(service: CodeGenerationService): void {
  codeGenerationInstance = service;
}
