from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from tools.devops.github_agent import GitHubAgent

# বাংলা মন্তব্য: GitHub API mock করে টেস্ট — real network call নেই।


@pytest.mark.asyncio
async def test_github_agent_repo_connect():
    """বাংলা মন্তব্য: connect_repo সফলভাবে repo metadata রিটার্ন করে কিনা টেস্ট।"""
    agent = GitHubAgent(token="mock-token-abc123")

    mock_resp = MagicMock()
    mock_resp.status_code = 200
    mock_resp.json.return_value = {"default_branch": "main"}
    mock_resp.raise_for_status = MagicMock()

    mock_client = AsyncMock()
    mock_client.get = AsyncMock(return_value=mock_resp)
    mock_client.__aenter__ = AsyncMock(return_value=mock_client)
    mock_client.__aexit__ = AsyncMock(return_value=None)

    with patch("tools.devops.github_agent.httpx.AsyncClient", return_value=mock_client):
        res = await agent.connect_repo("test-owner", "test-repo")

    assert res["status"] == "success"


@pytest.mark.asyncio
async def test_github_agent_analyze():
    """বাংলা মন্তব্য: analyze_repo সঠিক keys সহ dict রিটার্ন করে কিনা টেস্ট।"""
    agent = GitHubAgent(token="mock-token-abc123")

    mock_resp = MagicMock()
    mock_resp.status_code = 200
    mock_resp.json.return_value = {
        "open_issues_count": 5,
        "language": "Python",
        "default_branch": "main",
    }
    mock_resp.raise_for_status = MagicMock()

    mock_client = AsyncMock()
    mock_client.get = AsyncMock(return_value=mock_resp)
    mock_client.__aenter__ = AsyncMock(return_value=mock_client)
    mock_client.__aexit__ = AsyncMock(return_value=None)

    with patch("tools.devops.github_agent.httpx.AsyncClient", return_value=mock_client):
        analysis = await agent.analyze_repo("test/repo")

    assert "open_issues" in analysis
    # বাংলা মন্তব্য: deep static scoring এখনো implemented নয় — None রিটার্ন করে।
    assert analysis.get("primary_language") == "Python"


@pytest.mark.asyncio
async def test_github_agent_pr_creation():
    """বাংলা মন্তব্য: commit_changes এবং create_pr মক করে PR creation flow যাচাই।"""
    agent = GitHubAgent(token="mock-token-abc123")
    improvements = {"src/db.py": "Optimize pooling"}

    # বাংলা মন্তব্য: commit_changes এবং create_pr উভয় mock করা হচ্ছে।
    branch_name = "supremeai-improvements-20260726"
    with (
        patch.object(
            agent,
            "commit_changes",
            new=AsyncMock(
                return_value={
                    "status": "success",
                    "branch": branch_name,
                    "commit_hash": "abc123",
                    "files_committed": list(improvements),
                }
            ),
        ),
        patch.object(
            agent,
            "create_pr",
            new=AsyncMock(
                return_value={
                    "status": "success",
                    "pr_url": "https://github.com/test/repo/pull/1",
                    "pr_number": 1,
                }
            ),
        ),
    ):
        commit_res = await agent.commit_changes(
            repo_url="test/repo",
            files_to_commit=improvements,
            commit_message="SupremeAI: Auto-improvement patch",
            branch=branch_name,
        )
        pr_res = await agent.create_pr(
            repo_name="test/repo",
            title="Auto-improvement PR",
            body="Generated by SupremeAI",
            head_branch=branch_name,
        )

    res = {**commit_res, **pr_res}
    assert res["status"] == "success"
    assert "supremeai-improvements" in res["branch"]
    assert "pr_url" in res
