"""
SupremeAI 2.0 — Local AI Audit Runner
=====================================
Automates local LLM auditing of the 12 generated modular audit markdowns using
Ollama (local offline) or free-tier APIs (Gemini / Groq / OpenRouter / DeepSeek).

Bangla inline comments included as per AGENTS.md requirements.
"""

import argparse
import json
import os
import urllib.request
from pathlib import Path

# বাংলা নির্দেশিকা: প্রম্পট যা যেকোনো AI মডেলে পাঠানো হবে
AUDIT_SYSTEM_PROMPT = """You are an elite Autonomous AI Code Architect auditing SupremeAI 2.0.
Your task is to audit the attached self-contained markdown file containing complete source code dumps.

Check for:
1. Security vulnerabilities & secret leaks.
2. Silent exceptions & unhandled failure edge-cases.
3. Free-tier quota exhaustion risks.
4. Code quality & performance bottlenecks.

Output your findings clearly in GitHub-style Markdown with Section 4 (Vulnerabilities) and Section 5 (Recommended Delta Patches).
"""


def audit_file_with_ollama(markdown_path: Path, model_name: str = "llama3.2") -> str:
    """
    Executes audit using local Ollama instance (HTTP API).
    বাংলা মন্তব্য: লোকাল Ollama HTTP API ব্যবহার করে অফলাইনে সম্পূর্ণ ফ্রিতে অডিট সম্পন্ন করে।
    """
    file_content = markdown_path.read_text(encoding="utf-8", errors="ignore")
    prompt = (
        f"{AUDIT_SYSTEM_PROMPT}\n\n---\n\nAUDIT DOCUMENT CONTENT:\n\n{file_content}"
    )

    url = "http://localhost:11434/api/generate"
    payload = json.dumps(
        {"model": model_name, "prompt": prompt, "stream": False}
    ).encode("utf-8")

    req = urllib.request.Request(
        url, data=payload, headers={"Content-Type": "application/json"}
    )
    try:
        with urllib.request.urlopen(req, timeout=300) as response:
            res_data = json.loads(response.read().decode("utf-8"))
            return res_data.get("response", "No response received from Ollama.")
    except Exception as exc:
        return (
            f"Ollama execution error: {exc}. Ensure Ollama is running (`ollama serve`)."
        )


def audit_file_with_gemini_api(markdown_path: Path, api_key: str) -> str:
    """
    Executes audit using free-tier Gemini API (HTTP REST).
    বাংলা মন্তব্য: ফ্রি Gemini API ব্যবহার করে খুব দ্রুত অডিট সম্পূর্ণ করে।
    """
    file_content = markdown_path.read_text(encoding="utf-8", errors="ignore")
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={api_key}"

    payload = json.dumps(
        {
            "contents": [
                {
                    "parts": [
                        {"text": AUDIT_SYSTEM_PROMPT},
                        {
                            "text": f"Document File: {markdown_path.name}\n\n{file_content}"
                        },
                    ]
                }
            ]
        }
    ).encode("utf-8")

    req = urllib.request.Request(
        url, data=payload, headers={"Content-Type": "application/json"}
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as response:
            res_data = json.loads(response.read().decode("utf-8"))
            candidates = res_data.get("candidates", [])
            if candidates:
                return candidates[0]["content"]["parts"][0]["text"]
            return "No response text generated by Gemini API."
    except Exception as exc:
        return f"Gemini API execution error: {exc}"


def run_local_audit(
    target_part: str = "PART_03_MULTI_DB_OUTBOX.md",
    provider: str = "ollama",
    model: str = "llama3.2",
) -> None:
    """
    Reads markdown file and runs local LLM audit.
    বাংলা মন্তব্য: অডিট ফাইলটি লোকাল ডিভাইস থেকে পেস্ট না করে স্ক্রিপ্টের মাধ্যমে অটো রান করায়।
    """
    audit_dir = Path("docs/01-admin-plans/modular_audits").resolve()
    target_file = audit_dir / target_part

    if not target_file.exists():
        print(f"Error: Target audit file {target_file} does not exist.")
        return

    print(
        f"🚀 Running Local AI Audit on: {target_file.name} (Provider: {provider}, Model: {model})..."
    )

    if provider.lower() == "ollama":
        result = audit_file_with_ollama(target_file, model_name=model)
    elif provider.lower() == "gemini":
        api_key = os.getenv("GEMINI_API_KEY", "")
        if not api_key:
            print("Error: GEMINI_API_KEY environment variable not set.")
            return
        result = audit_file_with_gemini_api(target_file, api_key=api_key)
    else:
        print(f"Unknown provider: {provider}")
        return

    report_path = audit_dir / f"REPORT_{target_file.stem}.md"
    report_path.write_text(result, encoding="utf-8")
    print(f"✅ Local Audit Completed! Saved findings report to: {report_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="SupremeAI Local AI Audit Runner")
    parser.add_argument(
        "--file",
        default="PART_03_MULTI_DB_OUTBOX.md",
        help="Audit markdown file name in modular_audits/",
    )
    parser.add_argument(
        "--provider", default="ollama", choices=["ollama", "gemini"], help="AI Provider"
    )
    parser.add_argument("--model", default="llama3.2", help="Ollama model name")
    args = parser.parse_args()

    run_local_audit(target_part=args.file, provider=args.provider, model=args.model)
