"""add_sentinel_morphic_schema

Revision ID: cfe7c95dbee2
Revises: ed9761fee64f
Create Date: 2026-07-12 19:04:12.613450

"""

from collections.abc import Sequence

import sqlalchemy as sa
import utils.uuid_gen
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cfe7c95dbee2"
down_revision: str | Sequence[str] | None = "ed9761fee64f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_endpoints",
        sa.Column("id", utils.uuid_gen.UUIDv7(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("expected_status", sa.Integer(), nullable=True),
        sa.Column("is_critical", sa.Boolean(), nullable=True),
        sa.Column("last_ping_status", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("last_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dynamic_agents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("execution_steps", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dynamic_agents_id"), "dynamic_agents", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_dynamic_agents_name"), "dynamic_agents", ["name"], unique=True
    )
    op.create_table(
        "dynamic_capabilities",
        sa.Column("id", utils.uuid_gen.UUIDv7(), nullable=False),
        sa.Column("capability_name", sa.Text(), nullable=True),
        sa.Column("code_blob", sa.Text(), nullable=True),
        sa.Column("success_rate", sa.Float(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("is_auto_generated", sa.Boolean(), nullable=True),
        sa.Column("is_approved", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "execution_chains",
        sa.Column("id", utils.uuid_gen.UUIDv7(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=True),
        sa.Column("chain_of_thought", sa.Text(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("model_provider", sa.Text(), nullable=True),
        sa.Column(
            "raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_dependencies",
        sa.Column("id", utils.uuid_gen.UUIDv7(), nullable=False),
        sa.Column("package_name", sa.Text(), nullable=False),
        sa.Column("current_version", sa.Text(), nullable=False),
        sa.Column("latest_version", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("last_audit_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_incidents",
        sa.Column("id", utils.uuid_gen.UUIDv7(), nullable=False),
        sa.Column("incident_type", sa.Text(), nullable=True),
        sa.Column("severity", sa.Text(), nullable=True),
        sa.Column("is_auto_resolved", sa.Boolean(), nullable=True),
        sa.Column("remediation_log", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agent_reflections",
        sa.Column("id", utils.uuid_gen.UUIDv7(), nullable=False),
        sa.Column("agent_id", sa.Integer(), nullable=True),
        sa.Column("task_id", sa.String(), nullable=True),
        sa.Column("outcome_summary", sa.Text(), nullable=True),
        sa.Column(
            "learned_patterns", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["dynamic_agents.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_configs",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("provider_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "rpm",
            sa.INTEGER(),
            server_default=sa.text("999999"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "tpm",
            sa.INTEGER(),
            server_default=sa.text("999999"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "rpd",
            sa.INTEGER(),
            server_default=sa.text("999999"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "priority",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("provider_configs_pkey")),
        sa.UniqueConstraint(
            "provider_name",
            name=op.f("provider_configs_provider_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "messages",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("conversations_pkey")),
        sa.UniqueConstraint(
            "session_id",
            name=op.f("conversations_session_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "api_key_events",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("api_key_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("event_type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("details", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("ip_address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_keys.id"],
            name=op.f("api_key_events_api_key_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("api_key_events_pkey")),
    )
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "theme",
            sa.TEXT(),
            server_default=sa.text("'dark'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "default_model",
            sa.TEXT(),
            server_default=sa.text("'gpt-4o'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "max_tokens",
            sa.INTEGER(),
            server_default=sa.text("4096"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "auto_save",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "custom_shortcuts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("user_preferences_pkey")),
    )
    op.create_index(
        op.f("idx_user_preferences_updated_at"),
        "user_preferences",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "transaction_ledger",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "transaction_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "user_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "amount_usd",
            sa.NUMERIC(precision=10, scale=6),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "transaction_type",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "description", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("transaction_ledger_pkey")),
        sa.UniqueConstraint(
            "transaction_id",
            name=op.f("transaction_ledger_transaction_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_user_time"),
        "transaction_ledger",
        ["user_id", "timestamp"],
        unique=False,
    )
    op.create_table(
        "api_key_usage",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("api_key_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("endpoint", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("status_code", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "latency_ms",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("ip_address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_keys.id"],
            name=op.f("api_key_usage_api_key_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("api_key_usage_pkey")),
    )
    op.create_index(
        op.f("idx_api_key_usage_key"),
        "api_key_usage",
        ["api_key_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "feature_flags",
        sa.Column("feature_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "enabled",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "rollout_percentage",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "allowed_users",
            postgresql.ARRAY(sa.TEXT()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.CheckConstraint(
            "rollout_percentage >= 0 AND rollout_percentage <= 100",
            name=op.f("feature_flags_rollout_percentage_check"),
        ),
        sa.PrimaryKeyConstraint("feature_name", name=op.f("feature_flags_pkey")),
    )
    op.create_table(
        "guardrails",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("layer_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "rule_definition",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("guardrails_pkey")),
        sa.UniqueConstraint(
            "layer_name",
            name=op.f("guardrails_layer_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "github_repos",
        sa.Column("id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("owner", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "stars",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("language", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "last_indexed",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("category", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("priority", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("purpose", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("install_command", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            sa.TEXT(),
            server_default=sa.text("'active'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "added_date",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "priority = ANY (ARRAY['critical'::text, 'high'::text, 'medium'::text, 'low'::text])",
            name=op.f("github_repos_priority_check"),
        ),
        sa.CheckConstraint(
            "status = ANY (ARRAY['active'::text, 'archived'::text, 'deprecated'::text])",
            name=op.f("github_repos_status_check"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("github_repos_pkey")),
    )
    op.create_index(
        op.f("idx_github_repos_stars"),
        "github_repos",
        [sa.literal_column("stars DESC")],
        unique=False,
    )
    op.create_table(
        "learned_facts",
        sa.Column("id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "content",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("learned_facts_pkey")),
    )
    op.create_table(
        "agent_configs",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "agent_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "config_json",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.VARCHAR(length=50),
            server_default=sa.text("'active'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("agent_configs_pkey")),
        sa.UniqueConstraint(
            "agent_name",
            name=op.f("agent_configs_agent_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "markdown_exports",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("repo_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("time_range", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("status", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("timestamp", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("markdown_exports_pkey")),
        sa.UniqueConstraint(
            "job_id",
            name=op.f("markdown_exports_job_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "ai_model_behavior",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("model_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "behavior",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("ai_model_behavior_pkey")),
        sa.UniqueConstraint(
            "model_name",
            name=op.f("ai_model_behavior_model_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "trading_portfolio",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "portfolio",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("trading_portfolio_pkey")),
    )
    op.create_table(
        "feedback_loop",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("query", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("retrieved_chunks", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("user_rating", sa.REAL(), autoincrement=False, nullable=True),
        sa.Column(
            "adjusted",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("feedback_loop_pkey")),
    )
    op.create_table(
        "user_wallets",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "user_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "balance_usd",
            sa.NUMERIC(precision=10, scale=6),
            server_default=sa.text("0.000000"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "monthly_allowance_usd",
            sa.NUMERIC(precision=10, scale=6),
            server_default=sa.text("0.000000"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "version",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_wallets_pkey")),
        sa.UniqueConstraint(
            "user_id",
            name=op.f("user_wallets_user_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "domain_profiles",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("domain_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "profile",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("domain_profiles_pkey")),
    )
    op.create_table(
        "dynamic_skills",
        sa.Column(
            "skill_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("author_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("code", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "language",
            sa.TEXT(),
            server_default=sa.text("'python'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.TEXT(),
            server_default=sa.text("'pending'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "network_access",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "resource_limit_memory",
            sa.TEXT(),
            server_default=sa.text("'128m'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "resource_limit_cpu",
            sa.NUMERIC(precision=3, scale=2),
            server_default=sa.text("0.5"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "timeout_seconds",
            sa.INTEGER(),
            server_default=sa.text("30"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "sandbox_required",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("approved_by", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "approved_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "usage_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "failure_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("skill_id", name=op.f("dynamic_skills_pkey")),
    )
    op.create_index(
        op.f("idx_dynamic_skills_status"), "dynamic_skills", ["status"], unique=False
    )
    op.create_table(
        "system_config",
        sa.Column("key", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "value",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "category", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("system_config_pkey")),
    )
    op.create_index(op.f("ix_system_config_key"), "system_config", ["key"], unique=True)
    op.create_table(
        "offline_sync_logs",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("session_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("action_type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.TEXT(),
            server_default=sa.text("'synced'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "synced_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "status = ANY (ARRAY['pending'::text, 'synced'::text, 'failed'::text])",
            name=op.f("offline_sync_logs_status_check"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("offline_sync_logs_pkey")),
    )
    op.create_index(
        op.f("idx_offline_sync_user"), "offline_sync_logs", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_offline_sync_status"), "offline_sync_logs", ["status"], unique=False
    )
    op.create_table(
        "skill_fitness",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "skill_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "success_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "failure_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "fitness_score",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0.0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_run_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "version",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("skill_fitness_pkey")),
        sa.UniqueConstraint(
            "skill_name",
            name=op.f("skill_fitness_skill_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_skill_fitness_score"),
        "skill_fitness",
        [sa.literal_column("fitness_score DESC")],
        unique=False,
    )
    op.create_table(
        "credit_ledger",
        sa.Column("tx_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "amount",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("reason", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "balance_after",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("tx_id", name=op.f("credit_ledger_pkey")),
    )
    op.create_index(op.f("idx_ledger_user"), "credit_ledger", ["user_id"], unique=False)
    op.create_table(
        "tenant_limits",
        sa.Column("tenant_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("org_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "requests_per_minute",
            sa.INTEGER(),
            server_default=sa.text("60"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "max_tokens_per_day",
            sa.INTEGER(),
            server_default=sa.text("100000"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "max_concurrent_sessions",
            sa.INTEGER(),
            server_default=sa.text("5"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "billing_tier",
            sa.TEXT(),
            server_default=sa.text("'free'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("stripe_customer_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "custom_limits",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "billing_tier = ANY (ARRAY['free'::text, 'starter'::text, 'pro'::text, 'enterprise'::text])",
            name=op.f("tenant_limits_billing_tier_check"),
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("tenant_limits_pkey")),
    )
    op.create_table(
        "code_proposals",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "proposal_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "skill_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("generated_code", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "ast_validated",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "ci_passed",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.VARCHAR(length=50),
            server_default=sa.text("'proposed'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "version",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("code_proposals_pkey")),
        sa.UniqueConstraint(
            "proposal_id",
            name=op.f("code_proposals_proposal_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_proposal_status"), "code_proposals", ["status"], unique=False
    )
    op.create_table(
        "audit_logs_2026_06",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("action", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("tool_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("model", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("tokens_input", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("tokens_output", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "cost",
            sa.NUMERIC(precision=10, scale=6),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("latency_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("status", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint(
            "id", "timestamp", name=op.f("audit_logs_2026_06_pkey")
        ),
    )
    op.create_index(
        op.f("audit_logs_2026_06_user_id_idx"),
        "audit_logs_2026_06",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "credit_wallets",
        sa.Column("user_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "balance",
            sa.NUMERIC(precision=10, scale=2),
            server_default=sa.text("0.0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "lifetime_earned",
            sa.NUMERIC(precision=10, scale=2),
            server_default=sa.text("0.0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("credit_wallets_pkey")),
    )
    op.create_table(
        "provider_benchmarks",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("provider_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("latency_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("cost", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("provider_benchmarks_pkey")),
    )
    op.create_table(
        "skills",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "skill_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("code", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            sa.VARCHAR(length=50),
            server_default=sa.text("'active'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "version",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("skills_pkey")),
        sa.UniqueConstraint(
            "skill_name",
            name=op.f("skills_skill_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "referral_codes",
        sa.Column("code", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("referrer_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            sa.TEXT(),
            server_default=sa.text("'active'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "redeemed_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "fraud_score",
            sa.NUMERIC(precision=4, scale=2),
            server_default=sa.text("0.0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("(now() + '30 days'::interval)"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "status = ANY (ARRAY['active'::text, 'expired'::text, 'disabled'::text])",
            name=op.f("referral_codes_status_check"),
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("referral_codes_pkey")),
    )
    op.create_index(
        op.f("idx_referral_codes_status"), "referral_codes", ["status"], unique=False
    )
    op.create_index(
        op.f("idx_referral_codes_referrer"),
        "referral_codes",
        ["referrer_id"],
        unique=False,
    )
    op.create_table(
        "skill_proposals",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("skill_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("source_pattern", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("generated_code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            sa.TEXT(),
            server_default=sa.text("'proposed'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "registered_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("skill_proposals_pkey")),
    )
    op.create_table(
        "tenant_usage",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "date",
            sa.DATE(),
            server_default=sa.text("CURRENT_DATE"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "requests_today",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "tokens_today",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "cost_today",
            sa.NUMERIC(precision=10, scale=4),
            server_default=sa.text("0.0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant_limits.tenant_id"],
            name=op.f("tenant_usage_tenant_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("tenant_usage_pkey")),
        sa.UniqueConstraint(
            "tenant_id",
            "date",
            name=op.f("tenant_usage_tenant_id_date_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_tenant_usage_date"),
        "tenant_usage",
        ["tenant_id", "date"],
        unique=False,
    )
    op.create_table(
        "ci_reports",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("run_number", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "event_name", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "workflow_name", sa.VARCHAR(length=150), autoincrement=False, nullable=True
        ),
        sa.Column("status", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("runtime_seconds", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "commit_sha", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column("branch", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "jobs_summary",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("error_logs", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("ci_reports_pkey")),
        sa.UniqueConstraint(
            "run_id",
            name=op.f("ci_reports_run_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_ci_reports_run_id"), "ci_reports", ["run_id"], unique=False
    )
    op.create_index(
        op.f("idx_ci_reports_created"),
        "ci_reports",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "task_history",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("task", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("approach", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("result", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("success", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("task_history_pkey")),
    )
    op.create_table(
        "rules",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "rule_key", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "category", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("value", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "is_enabled",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("rules_pkey")),
        sa.UniqueConstraint(
            "rule_key",
            name=op.f("rules_rule_key_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "usage_metrics",
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "total_requests",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "total_tokens",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "total_cost",
            sa.NUMERIC(precision=10, scale=2),
            server_default=sa.text("0.00"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "unique_users",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "avg_latency_ms",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "error_rate",
            sa.NUMERIC(precision=5, scale=2),
            server_default=sa.text("0.00"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("date", name=op.f("usage_metrics_pkey")),
    )
    op.create_index(
        op.f("idx_usage_metrics_date"),
        "usage_metrics",
        [sa.literal_column("date DESC")],
        unique=False,
    )
    op.create_table(
        "evolution_logs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "event",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("evolution_logs_pkey")),
    )
    op.create_table(
        "tools_registry",
        sa.Column("tool_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "version",
            sa.TEXT(),
            server_default=sa.text("'1.0.0'::text"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("file_path", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("category", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "cost_per_call",
            sa.NUMERIC(precision=10, scale=6),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "success_rate",
            sa.NUMERIC(precision=3, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("avg_latency_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "total_calls",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("tool_id", name=op.f("tools_registry_pkey")),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("key_hash", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("key_masked", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("key_prefix", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "rate_limit_rps",
            sa.INTEGER(),
            server_default=sa.text("6"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "revoked",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("expires_at", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("last_used_at", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("updated_at", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("api_keys_pkey")),
        sa.UniqueConstraint(
            "key_hash",
            name=op.f("api_keys_key_hash_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("idx_api_keys_hash"), "api_keys", ["key_hash"], unique=False)
    op.create_table(
        "offline_sync_conflicts",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("sync_log_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("conflict_type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "server_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "client_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("resolution", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "resolved_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "resolution = ANY (ARRAY['server_wins'::text, 'client_wins'::text, 'manual'::text, 'pending'::text])",
            name=op.f("offline_sync_conflicts_resolution_check"),
        ),
        sa.ForeignKeyConstraint(
            ["sync_log_id"],
            ["offline_sync_logs.id"],
            name=op.f("offline_sync_conflicts_sync_log_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("offline_sync_conflicts_pkey")),
    )
    op.create_table(
        "sso_sessions",
        sa.Column("session_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("email", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "roles",
            postgresql.ARRAY(sa.TEXT()),
            server_default=sa.text("'{}'::text[]"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "groups",
            postgresql.ARRAY(sa.TEXT()),
            server_default=sa.text("'{}'::text[]"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("method", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("idp_session_index", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("sso_sessions_pkey")),
    )
    op.create_index(
        op.f("idx_sso_sessions_user"), "sso_sessions", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_sso_sessions_tenant"), "sso_sessions", ["tenant_id"], unique=False
    )
    op.create_table(
        "referral_redemptions",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("referrer_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("new_user_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "reward_amount",
            sa.NUMERIC(precision=10, scale=2),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "credits_awarded",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("platform", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["code"],
            ["referral_codes.code"],
            name=op.f("referral_redemptions_code_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("referral_redemptions_pkey")),
    )
    op.create_index(
        op.f("idx_redemptions_referrer"),
        "referral_redemptions",
        ["referrer_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_redemptions_new_user"),
        "referral_redemptions",
        ["new_user_id"],
        unique=False,
    )
    op.create_table(
        "sso_configs",
        sa.Column("tenant_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("provider", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("sp_entity_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("acs_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("sls_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("idp_entity_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("idp_sso_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("idp_slo_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("idp_x509_cert", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("oidc_client_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("oidc_client_secret", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("oidc_redirect_uri", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("oidc_domain", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("oidc_tenant", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "role_mappings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "enabled",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint(
            "provider = ANY (ARRAY['saml'::text, 'oidc'::text, 'google'::text, 'azure'::text, 'okta'::text])",
            name=op.f("sso_configs_provider_check"),
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("sso_configs_pkey")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("action", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("tool_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("model", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("tokens_input", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("tokens_output", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "cost",
            sa.NUMERIC(precision=10, scale=6),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("latency_ms", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("status", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", "timestamp", name=op.f("audit_logs_pkey")),
    )
    op.create_index(
        op.f("idx_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False
    )
    # ### end Alembic commands ###
