package com.supremeai.service.learning;

import org.springframework.stereotype.Service;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

@Service
public class CodeImmunitySystem {

    // This would typically be persisted to system_configs/code_immunity.json
    private final List<String> immunityPatterns = new CopyOnWriteArrayList<>();

    /**
     * Learns from a failed code execution by extracting a signature.
     * 
     * @param buggyCode The code snippet that caused an error.
     */
    public void immunize(String buggyCode) {
        if (buggyCode == null || buggyCode.isBlank())
            return;

        // World-class abstraction logic:
        // 1. Normalize whitespace
        // 2. Escape regex meta-characters
        // 3. Create a structural match pattern
        String normalized = buggyCode.trim().replaceAll("\\s+", " ");
        String escaped = Pattern.quote(normalized);

        // Convert generic parts back to wildcards to match structural variations
        // Example: variable names or minor spacing
        String logicSignature = escaped.replace("\\ ", "\\s+");

        if (!immunityPatterns.contains(logicSignature)) {
            immunityPatterns.add(logicSignature);
        }
    }

    /**
     * Validates if the proposed code is "immune" (safe) from known buggy patterns.
     * 
     * @param proposedCode Code generated by the AI.
     * @return true if the code does NOT match any failed patterns.
     */
    public boolean isSafe(String proposedCode) {
        String flatCode = proposedCode.replaceAll("\\s+", " ");

        return immunityPatterns.stream()
                .noneMatch(pattern -> Pattern.compile(pattern).matcher(flatCode).find());
    }

    public List<String> getActiveImmunities() {
        return List.copyOf(immunityPatterns);
    }
}