from datetime import datetime

from pydantic import BaseModel
from pydantic import Field


class VoiceInteractionMetadata(BaseModel):
    user_id: str = Field(..., description="ID of the user who initiated the command")
    audio_format: str = Field(default="webm", description="Format of the uploaded audio chunk")
    duration_ms: int = Field(default=0, description="Duration of the audio chunk in milliseconds")


class VoiceInteractionLog(BaseModel):
    id: str | None = None
    user_id: str
    transcript: str = Field(..., description="The STT parsed text from the user")
    supremeai_response: str = Field(..., description="The textual response generated by the AI")
    stt_provider: str = Field(default="groq-whisper", description="Engine used for STT")
    latency_ms: int = Field(default=0, description="Total round-trip latency")
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        json_schema_extra = {
            "example": {
                "user_id": "admin-01",
                "transcript": "Execute deployment check on Node 47.",
                "supremeai_response": "Analyzing Node 47. Status: Nominal.",
                "stt_provider": "groq-whisper",
                "latency_ms": 120
            }
        }
