{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-websocket",
    "version": "3.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-websocket",
          "version": {
            "requires": "6.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-websocket-3.2.3.jar",
          "url": "spring-boot-starter-websocket-3.2.3.jar",
          "size": 4783,
          "sha512": "ef84c54409fccbe316e8425a08ded80ed919fc4951e2538f640138189a14a5906f36d32f481b889a1165aa77bea8e7c29330f4d4bb4d11b69bf52faf157f35f4",
          "sha256": "51279d7c89fda1004f886b2cf9261dcff16b55e3e47d972b91e085a46f6dd360",
          "sha1": "343ca88da40fbd06b6d4b3d4b86fb1bdc5d80a09",
          "md5": "e46b668f03fbf17a03aa9b5ab9f0bfe4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-websocket",
          "version": {
            "requires": "6.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-websocket-3.2.3.jar",
          "url": "spring-boot-starter-websocket-3.2.3.jar",
          "size": 4783,
          "sha512": "ef84c54409fccbe316e8425a08ded80ed919fc4951e2538f640138189a14a5906f36d32f481b889a1165aa77bea8e7c29330f4d4bb4d11b69bf52faf157f35f4",
          "sha256": "51279d7c89fda1004f886b2cf9261dcff16b55e3e47d972b91e085a46f6dd360",
          "sha1": "343ca88da40fbd06b6d4b3d4b86fb1bdc5d80a09",
          "md5": "e46b668f03fbf17a03aa9b5ab9f0bfe4"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-websocket-3.2.3.jar",
          "url": "spring-boot-starter-websocket-3.2.3.jar",
          "size": 4783,
          "sha512": "ef84c54409fccbe316e8425a08ded80ed919fc4951e2538f640138189a14a5906f36d32f481b889a1165aa77bea8e7c29330f4d4bb4d11b69bf52faf157f35f4",
          "sha256": "51279d7c89fda1004f886b2cf9261dcff16b55e3e47d972b91e085a46f6dd360",
          "sha1": "343ca88da40fbd06b6d4b3d4b86fb1bdc5d80a09",
          "md5": "e46b668f03fbf17a03aa9b5ab9f0bfe4"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-websocket-maven-optional",
          "version": "3.2.3"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-websocket-3.2.3.jar",
          "url": "spring-boot-starter-websocket-3.2.3.jar",
          "size": 4783,
          "sha512": "ef84c54409fccbe316e8425a08ded80ed919fc4951e2538f640138189a14a5906f36d32f481b889a1165aa77bea8e7c29330f4d4bb4d11b69bf52faf157f35f4",
          "sha256": "51279d7c89fda1004f886b2cf9261dcff16b55e3e47d972b91e085a46f6dd360",
          "sha1": "343ca88da40fbd06b6d4b3d4b86fb1bdc5d80a09",
          "md5": "e46b668f03fbf17a03aa9b5ab9f0bfe4"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-websocket-maven-optional",
          "version": "3.2.3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-websocket-3.2.3-javadoc.jar",
          "url": "spring-boot-starter-websocket-3.2.3-javadoc.jar",
          "size": 4746,
          "sha512": "c299890c90720c2fb9a8e211d8639747da2c9f8eea71547246dd815b5a64878a04b3c0a0aaac1be23fa460c73cc800742ce1f2eba44d4c0d0f86bd3c521ab6af",
          "sha256": "3ab2e0de21200e33af470c14af4c677a8c6611ce4878026fe0c52120031ae573",
          "sha1": "4582f6500c320332a4cc5347cea91d8f9a01e3e1",
          "md5": "13030101e93a29675b6e01804ef4f524"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-websocket-3.2.3-sources.jar",
          "url": "spring-boot-starter-websocket-3.2.3-sources.jar",
          "size": 4745,
          "sha512": "7cf54a84efcc57ebb5675990e74ec64ed7b2a833412881a88714aa9747290d76979534338fe3227071609c514dd5caab8a0bea03ceff6bd07a0f6964bdab1d6b",
          "sha256": "1338475ecfa9d9b6158b850ff0563da6b0d233e559aa71330b6b8b63cf3ff9da",
          "sha1": "70a28e7280100684ba185b5230bc365ed10fbb47",
          "md5": "1403e0d4c4fd6f0ed05611b10c78a063"
        }
      ]
    }
  ]
}
