import asyncio
import uuid

from fastapi import APIRouter, Depends, HTTPException
from github import Github  # PyGithub library
from github import GithubException
from loguru import logger
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession

from api.dependencies import get_current_user_token
from core.error_bus import with_error_bus
from core.messaging.pubsub import global_pubsub
from database.session import get_db_session
from tools.devops.github_agent import get_user_github_token

router = APIRouter(tags=["Dock Actions"])


class DockActionPayload(BaseModel):
    triggered_from: str
    active_file: str | None = None
    content: str | None = None  # যে কোডটি গিটহাবে যাবে


# push_to_sse implemented using the global pubsub in your event system
async def push_to_sse(session_id: str, data: dict):
    await global_pubsub.publish(
        "dashboard_events",
        {"type": "integration_status", "payload": {"session_id": session_id, **data}},
    )


# গ্যাপ #1 সমাধান: auth আর কমেন্ট-আউট নয়
@router.post("/session/{session_id}/integrations/{tool_id}")
async def run_dock_integration(
    session_id: str,
    tool_id: str,
    payload: DockActionPayload,
    user: dict = Depends(get_current_user_token),
    sql_db: AsyncSession = Depends(get_db_session),
):
    # ১. UI তে "Neon-Pulse" অ্যানিমেশন অন করার জন্য SSE পুশ
    await push_to_sse(
        session_id,
        {"state": "processing", "message": f"Connecting to {tool_id.capitalize()}..."},
    )

    # ২. টুল ডিসপ্যাচার (Tool Dispatcher)
    if tool_id == "github":
        return await handle_github_push(session_id, payload, user, sql_db)
    elif tool_id == "slack":
        raise HTTPException(status_code=501, detail="Slack not implemented yet")
    else:
        await push_to_sse(session_id, {"state": "error", "message": "Unknown tool"})
        raise HTTPException(status_code=400, detail="Integration not supported")


# --- গিটহাব ইন্টিগ্রেশন লজিক ---
async def handle_github_push(session_id: str, payload: DockActionPayload, user: dict, sql_db: AsyncSession):
    try:
        # ধাপ ১: ইউজারের Vault থেকে গিটহাব টোকেন বের করা
        # গ্যাপ #3 সমাধান: হার্ডকোড করা placeholder টোকেনের বদলে repo-তে যে প্যাটার্ন ইতিমধ্যে
        # backend/api/routes/github.py-তে ব্যবহৃত হয়, সেটাই এখানে পুনর্ব্যবহার করা হলো —
        # প্রতিটি ইউজারের আসল, এনক্রিপ্টেড GitHub টোকেন DB/Vault থেকে টেনে আনা হয়।
        user_id = user.get("sub")
        if not user_id:
            raise HTTPException(status_code=401, detail="Unauthorized")

        user_token = await get_user_github_token(user_id, sql_db)
        if not user_token:
            raise HTTPException(
                status_code=403,
                detail="GitHub token missing! Please connect GitHub in your Vault/Integrations settings.",
            )

        # ধাপ ২: AI Agent দিয়ে কমিট মেসেজ জেনারেট করা
        file_name = payload.active_file or "snippet.ts"
        commit_message = f"🤖 SupremeAI Auto-Commit: Update {file_name}"
        file_content = payload.content or "// Auto-generated by SupremeAI Action Dock"

        # ধাপ ৩: গিটহাবে পুশ করা (PyGithub ম্যাজিক)
        await push_to_sse(
            session_id,
            {"state": "processing", "message": "Pushing code to repository..."},
        )

        # PyGithub ব্লকিং কল করে, তাই এটিকে async এ চালানোর জন্য একটু ট্রিকস:
        @with_error_bus("push_code")
        def push_code():
            g = Github(user_token)
            gh_user = g.get_user()
            # ইউজারের একটি ডিফল্ট রিপোজিটরি টার্গেট করুন, অথবা নতুন তৈরি করুন
            repo = gh_user.get_repo("supremeai_generated_workspace")

            try:
                # ফাইল আগে থাকলে আপডেট করবে, না থাকলে নতুন বানাবে
                contents = repo.get_contents(file_name)
                repo.update_file(
                    contents.path,
                    commit_message,
                    file_content,
                    contents.sha,
                    branch="main",
                )
            except GithubException as gh_exc:
                # গ্যাপ #2 সমাধান: শুধু "file not found" (404) কেসেই create_file এ ফলব্যাক করা উচিত।
                # আগের bare `except:` সব ধরনের এরর (auth ফেইলিউর, rate-limit, network issue, permission
                # ইত্যাদি) নীরবে গিলে ফেলে create_file কল করত — ভুল এরর মাস্ক করত এবং অপ্রত্যাশিত
                # ডুপ্লিকেট/কনফ্লিক্ট রিকোয়েস্ট পাঠানোর ঝুঁকি তৈরি করত।
                if gh_exc.status == 404:
                    repo.create_file(file_name, commit_message, file_content, branch="main")
                else:
                    raise

        # ব্যাকগ্রাউন্ড থ্রেডে গিটহাব এপিআই কল করা (যাতে ফাস্টএপিআই ব্লক না হয়)
        await asyncio.to_thread(push_code)

        # ধাপ ৪: UI তে সাকসেস মেসেজ ও গ্রিন টিক অ্যানিমেশন পাঠানো
        await push_to_sse(
            session_id,
            {"state": "success", "message": "Code successfully merged to GitHub!"},
        )

        return {"ok": True, "message": "Pushed to GitHub"}

    except HTTPException:
        raise
    except GithubException as e:
        error_id = uuid.uuid4().hex[:8]
        logger.error(f"[{error_id}] dock_actions/github push failed: {e}")
        await push_to_sse(
            session_id,
            {"state": "error", "message": f"GitHub API Error (ref: {error_id})"},
        )
        raise HTTPException(status_code=502, detail=f"GitHub operation failed (ref: {error_id})") from e
    except Exception as e:
        error_id = uuid.uuid4().hex[:8]
        logger.error(f"[{error_id}] dock_actions/github push failed: {e}")
        await push_to_sse(session_id, {"state": "error", "message": f"GitHub Error (ref: {error_id})"})
        raise HTTPException(status_code=500, detail=f"Internal error (ref: {error_id})") from e
