FROM ghcr.io/tgdrive/teldrive:latest AS teldrive-bin

FROM alpine:latest
RUN apk add --no-cache ca-certificates libc6-compat
COPY --from=teldrive-bin /teldrive /teldrive
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
EXPOSE 8080
ENTRYPOINT ["/entrypoint.sh"]
