{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-messaging",
    "version": "6.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-messaging-6.1.4.jar",
          "url": "spring-messaging-6.1.4.jar",
          "size": 614798,
          "sha512": "f5231c1392818f7fac5d4b3dda6e32d85ad3defc03cc3f709c169839394f5cece2bf79deceea175ab97f5d604727950fcb88a9cccf0b165b4855b4821c5c087f",
          "sha256": "3f84fa9a4963a1a1764a235ee76bb85af6012f1c2358a399ddaad065889d271e",
          "sha1": "6de5be83e0772acb48221b895f1d2324d1db500f",
          "md5": "425a90506466e2da4557e2f7a9b6a90e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-messaging-6.1.4.jar",
          "url": "spring-messaging-6.1.4.jar",
          "size": 614798,
          "sha512": "f5231c1392818f7fac5d4b3dda6e32d85ad3defc03cc3f709c169839394f5cece2bf79deceea175ab97f5d604727950fcb88a9cccf0b165b4855b4821c5c087f",
          "sha256": "3f84fa9a4963a1a1764a235ee76bb85af6012f1c2358a399ddaad065889d271e",
          "sha1": "6de5be83e0772acb48221b895f1d2324d1db500f",
          "md5": "425a90506466e2da4557e2f7a9b6a90e"
        }
      ]
    }
  ]
}
