apiVersion: 1

contactPoints:
  - orgId: 1
    name: supremeai-ops
    receivers:
      - uid: email-ops
        type: email
        settings:
          addresses: ops@supremeai.local
          singleEmail: false

policies:
  - orgId: 1
    receiver: supremeai-ops
    group_by:
      - alertname
      - severity
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
