name: Cleanup Old Workflow Runs
on:
  schedule:
    - cron: '0 0 * * *' # প্রতিদিন রাত ১২টায় (UTC) অটোমেটিকভাবে রান করবে
  workflow_dispatch:
    inputs:
      days:
        description: 'Days to keep runs'
        required: true
        default: '5'

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days || 5 }}
          keep_minimum_runs: 50
