name: SupremeAI Deploy

on:
  workflow_run:
    workflows: ["SupremeAI CI"]
    types: [completed]
    branches: [main, develop]

jobs:
  deploy-backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/reusable-java.yml
    with:
      deploy: true
    secrets:
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

  deploy-frontend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      firebase_project: 'supremeai-a'
    secrets:
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUPREMEAI_A }}
