name: Reusable Flutter CI

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.0'
        cache: true
    - working-directory: flutter_admin_app
      run: |
        flutter pub get
        flutter analyze
        flutter test
        flutter build web --release