name: Security Scan

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '34 7 * * 4'

jobs:
  codeql-analysis:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: java-kotlin

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      env:
        GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=false
      run: |
        chmod +x gradlew
        ./gradlew clean compileJava --no-build-cache

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3